### ISSUE TITLE
Erratic selection behavior when Tabs component has non-Tab components

### ISSUE THREAD

**Issue by rolandoisidoro** [vaadin/flow-components#1177]
The `Tabs` allows to add components other than `Tab` by using the `add(String text)` and `add(Component... components)` methods.

Given the following `Tabs` + `Tab` components based menu, with multiple `Tab` component instances, two `H3` components and one `HtmlComponent("hr")` component:

![image](https://user-images.githubusercontent.com/1101532/74264237-3d2a3c80-4cf8-11ea-9450-81733c045e15.png)

- Clicking on any `Tab` before any non-`Tab` components works as expected;
- Clicking the Buildings `Tab`, it shows as selected but a `IllegalStateException` is thrown (see vaadin/vaadin-tabs-flow#116):
```
java.lang.IllegalStateException: Illegal component inside Tabs: com.vaadin.flow.component.html.H3@6bd52dad
	at com.vaadin.flow.component.tabs.Tabs.getSelectedTab(Tabs.java:359)
	at com.vaadin.flow.component.tabs.Tabs.updateSelectedTab(Tabs.java:471)
```
- Clicking the Offices `Tab` selects the Buildings `Tab`;
- Clicking the Factories `Tab` selects the right one plus the Buildings `Tab`;

This strange behavior goes on, the more non-`Tab` components we add in between, the more spaced the selections become.

- Clicking the Tabs `Tab`, it shows as selected but a `IllegalStateException` is thrown:
```
java.lang.IllegalStateException: Illegal component inside Tabs: com.vaadin.flow.component.HtmlComponent@54dde0f6
	at com.vaadin.flow.component.tabs.Tabs.getSelectedTab(Tabs.java:359)
	at com.vaadin.flow.component.tabs.Tabs.updateSelectedTab(Tabs.java:471)
```
- Clicking the Records `Tab` selects the right one plus the Boards `Tab`.

I've tried to debug the issue of the double selection and found that the correct tab is selected in the [`updateSelectedTab`](https://github.com/vaadin/vaadin-tabs-flow/blob/master/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java#L485) method, while the second selection occurs when calling [`fireEvent`](https://github.com/vaadin/vaadin-tabs-flow/blob/master/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java#L488) in the same method.

**Comment by web-padawan** [comment]
> The Tabs allows to add components other than Tab by using the add(String text) and add(Component... components) methods.

Duplicate of https://github.com/vaadin/flow-components/issues/1636. Method is now deprecated and will be removed in V26. Closing.
