### ISSUE TITLE
MultiSelectListBox throws exception if value is not a subset of items

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow-components#1178]
`MultiSelectListBox` throws `ArrayIndexOutOfBoundsException` when `setValue` receives an item that is not listed among the component items. Compare with `CheckboxGroup`, which handles this case gracefully.

```
CheckboxGroup<String> cbg = new CheckboxGroup<>();
cbg.setItems(Collections.singleton("foo"));
cbg.setValue(Collections.singleton("bar"));
		
MultiSelectListBox<String> box = new MultiSelectListBox<>();
box.setItems(Collections.singleton("foo"));
box.setValue(Collections.singleton("bar"));
```

Vaadin version: 14.1.17

Stack trace:
```
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418) ~[na:1.8.0_144]
	at java.util.ArrayList.get(ArrayList.java:431) ~[na:1.8.0_144]
	at com.vaadin.flow.component.listbox.MultiSelectListBox.lambda$presentationToModel$1(MultiSelectListBox.java:61) ~[vaadin-list-box-flow-2.1.1.jar:na]
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250) ~[na:1.8.0_144]
	at java.util.stream.IntPipeline$3$1.accept(IntPipeline.java:233) ~[na:1.8.0_144]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) ~[na:1.8.0_144]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693) ~[na:1.8.0_144]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_144]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_144]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_144]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_144]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_144]
	at com.vaadin.flow.component.listbox.MultiSelectListBox.presentationToModel(MultiSelectListBox.java:62) ~[vaadin-list-box-flow-2.1.1.jar:na]
	at com.vaadin.flow.component.AbstractSinglePropertyField$TypeHandler.lambda$createReader$d15de0eb$1(AbstractSinglePropertyField.java:96) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.component.AbstractSinglePropertyField.handlePropertyChange(AbstractSinglePropertyField.java:349) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.component.AbstractSinglePropertyField.access$200(AbstractSinglePropertyField.java:48) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.component.AbstractSinglePropertyField$1.propertyChange(AbstractSinglePropertyField.java:325) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.lambda$fireEvent$2(ElementPropertyMap.java:453) ~[flow-server-2.1.4.jar:2.1.4]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_144]
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.fireEvent(ElementPropertyMap.java:453) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.access$100(ElementPropertyMap.java:48) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap$PutResult.run(ElementPropertyMap.java:164) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.put(ElementPropertyMap.java:146) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.internal.nodefeature.AbstractPropertyMap.setProperty(AbstractPropertyMap.java:60) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.setProperty(ElementPropertyMap.java:92) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.dom.impl.BasicElementStateProvider.setProperty(BasicElementStateProvider.java:268) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.dom.Element.setRawProperty(Element.java:793) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.dom.Element.setPropertyJson(Element.java:726) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.component.AbstractSinglePropertyField.lambda$getHandler$ff29eb77$1(AbstractSinglePropertyField.java:371) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.component.AbstractSinglePropertyField$TypeHandler.lambda$createWriter$db98900a$1(AbstractSinglePropertyField.java:114) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.component.AbstractSinglePropertyField.setPresentationValue(AbstractSinglePropertyField.java:359) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.component.internal.AbstractFieldSupport.applyValue(AbstractFieldSupport.java:220) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.component.internal.AbstractFieldSupport.setValue(AbstractFieldSupport.java:188) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.component.internal.AbstractFieldSupport.setValue(AbstractFieldSupport.java:133) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.component.AbstractField.setValue(AbstractField.java:181) ~[flow-server-2.1.4.jar:2.1.4]
	at com.vaadin.flow.component.listbox.MultiSelectListBox.setValue(MultiSelectListBox.java:92) ~[vaadin-list-box-flow-2.1.1.jar:na]
```

**Comment by web-padawan** [comment]
Could not reproduce the issue on master with the provided example. Looks like this has been fixed, closing.
