### ISSUE TITLE
Preserve record placement in the grid after editing and saving it in the database

### ISSUE THREAD

**Issue by xcsportskier** [vaadin/flow-components#1204]
I am trying to use Vaadin CRUD component in my application but I have an issue related with needing to preserve record placement in the grid after record been edited and saved in the database.

Here is an example deployed to AWS, which is demonstrating current behaviour: http://productdb-env.bvp6apbgir.us-east-2.elasticbeanstalk.com/products

Try to do follow:
1.  Order records by Quantity column value in descending order.
2. Scroll records down on two or three screens.
3. Start to edit any record and input into quantity field a value, which would be big enough, says 9999.
4. Save the record. Do you see? Edited record has gone and can be found now at top of the screen if you scroll up there.

What I want to do is to implement such behaviour then edited record after editing will stay where it is.

According your advices I changed the line at vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/Crud.java:207 
(https://github.com/vaadin/vaadin-crud-flow/blob/master/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/Crud.java#L207)

from refreshAll to refreshItem. After that I received the desired behaviour of component.

But I have a problem, because then I changed an operator from refreshAll to refreshItem, it gives me NullPointerException. It's not prevent application from execution, data are stored in database, everything seems to be fine, but on every edit attempt this error stack is written into log file:

java.lang.NullPointerException: Refreshed item can't be null
at java.util.Objects.requireNonNull(Objects.java:228) ~[na:1.8.0_77]
at com.vaadin.flow.data.provider.DataChangeEvent$DataRefreshEvent.<init>(DataChangeEvent.java:56) ~[flow-data-1.4.4.jar:1.4.4]
at com.vaadin.flow.data.provider.AbstractDataProvider.refreshItem(AbstractDataProvider.java:58) ~[flow-data-1.4.4.jar:1.4.4]
at com.vaadin.flow.component.customcrud.Crud.lambda$6(Crud.java:207) ~[vaadin-crud-flow-custom-2.0-SNAPSHOT.jar:na]
at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:205) ~[flow-server-1.4.4.jar:1.4.4]
at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:373) ~[flow-server-1.4.4.jar:1.4.4]
at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:264) ~[flow-server-1.4.4.jar:1.4.4]
at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:420) ~[flow-server-1.4.4.jar:1.4.4]
...

So, first, I hope your developers can explain how to overcome that.
And, second, I very do believe that CRUD component should implement both behaviours so that software developers could choose desirable. It would be fine if your developers add this possibility into public API for this component. From my experience every business user I have ever seen before goes mad and wants to kill software developer in case if edited record  disappears from the screen after editing.

You can find my project here: https://github.com/xcsportskier/SpringVaadin

**Comment by web-padawan** [comment]
Crud's save handler calls `getGrid().getDataProvider().refreshAll()`, which re-fetches and re-sorts the whole grid, so an edited record whose sort key changed moves. Making it configurable would require introducing new API.
