### ISSUE TITLE
Returning null in a ComponentRenderer

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/flow-components#1291]
If for some reason null is returned in the `SerializableFunction` sended as a parameter in the constructor of a ComponentRenderer, like in the following example:

```
		Grid<String> testGrid = new Grid<>();
		testGrid.addColumn(new ComponentRenderer<>(item-> {
			return null;
		}));
		testGrid.setItems(Arrays.asList("one","two","three"));
```
Then the following exception is produced:

```
Caused by: java.lang.NullPointerException
	at com.vaadin.flow.data.provider.AbstractComponentDataGenerator.registerRenderedComponent(AbstractComponentDataGenerator.java:110)
	at com.vaadin.flow.data.provider.ComponentDataGenerator.generateData(ComponentDataGenerator.java:80)
	at com.vaadin.flow.data.provider.CompositeDataGenerator.lambda$generateData$0(CompositeDataGenerator.java:47)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.vaadin.flow.data.provider.CompositeDataGenerator.generateData(CompositeDataGenerator.java:47)
	at com.vaadin.flow.data.provider.DataCommunicator.generateJson(DataCommunicator.java:644)

```
It can be avoided by just returning an empty label, but it could be confusing at times as it doesn't specify which column is generating the issue.

**Comment by Frettman** [comment]
Not having to create and return a new dummy components (which are held in memory) would be an even more important benefit than having to type a few characters less. Whether null is actually allowed or not could be a configuration of the ComponentRenderer.

**Comment by web-padawan** [comment]
Closing as duplicate of https://github.com/vaadin/flow-components/issues/1549 fixed by https://github.com/vaadin/flow-components/pull/4361.
