### ISSUE TITLE
Exception occurs when listening to HasSeries events on timeline charts

### ISSUE THREAD

**Issue by johannesh2** [vaadin/flow-components#1359]
When a single series is created on a timeline chart as done in this https://github.com/vaadin/vaadin-charts-flow/blob/master/examples/src/main/java/com/vaadin/flow/component/charts/examples/timeline/Candlestick.java#L25-L41 example, Highcharts generates two series: one for the timeline series and another for the navigator. Listening on `HasSeries` events therefore has the potential of throwing an exception if the event (e.g a mouse over) comes from the navigator.

**Comment by paodb** [comment]
This issue is still reproducible in Vaadin **25.3.0**.

The reproduction is based on the `Candlestick` timeline example referenced in the description. The chart has a single series on the server side. When `setTimeline(true)` is enabled, Highcharts adds an internal navigator series. Events coming from that series have `seriesIndex = 1`, so `HasSeries.getSeries()` fails with `IndexOutOfBoundsException`.

The exception is thrown by the `SeriesAfterAnimateEvent` listener as soon as the chart is rendered, with no user interaction needed.

### Steps to reproduce
1. Add the view below to a Vaadin 25.3.0 app.
2. Open the view.
3. The exception is thrown on chart load.

<details>
<summary>Reproduction code</summary>

```java
@Route("")
public class CandlestickHasSeriesView extends VerticalLayout {

    private final Pre eventLog = new Pre();

    public CandlestickHasSeriesView() {
        final Chart chart = new Chart(ChartType.CANDLESTICK);

        Configuration configuration = chart.getConfiguration();
        configuration.getTitle().setText("AAPL Stock Price");

        DataSeries dataSeries = new DataSeries();
        PlotOptionsCandlestick plotOptionsCandlestick = new PlotOptionsCandlestick();
        DataGrouping grouping = new DataGrouping();
        grouping.addUnit(new TimeUnitMultiples(TimeUnit.WEEK, 1));
        grouping.addUnit(new TimeUnitMultiples(TimeUnit.MONTH, 1, 2, 3, 4, 6));
        plotOptionsCandlestick.setDataGrouping(grouping);
        dataSeries.setPlotOptions(plotOptionsCandlestick);

        // Synthetic OHLC data instead of StockPrices.fetchAaplOhlcPrice()
        Random random = new Random(42);
        Instant date = Instant.parse("2020-01-01T00:00:00Z");
        double price = 100;
        for (int i = 0; i < 1000; i++) {
            double open = price;
            double close = open + random.nextGaussian() * 2;
            OhlcItem item = new OhlcItem();
            item.setX(date.plus(i, ChronoUnit.DAYS));
            item.setLow(Math.min(open, close) - random.nextDouble() * 2);
            item.setHigh(Math.max(open, close) + random.nextDouble() * 2);
            item.setClose(close);
            item.setOpen(open);
            dataSeries.add(item);
            price = close;
        }
        configuration.setSeries(dataSeries);

        RangeSelector rangeSelector = new RangeSelector();
        rangeSelector.setSelected(4);
        configuration.setRangeSelector(rangeSelector);

        chart.setTimeline(true);

        chart.addSeriesAfterAnimateListener(event -> handleEvent("afterAnimate", event));
        chart.addPointClickListener(event -> handleEvent("pointClick", event));
        chart.addPointMouseOverListener(event -> handleEvent("pointMouseOver", event));
        chart.addSeriesClickListener(event -> handleEvent("seriesClick", event));
        chart.addSeriesHideListener(event -> handleEvent("seriesHide", event));
        chart.addSeriesShowListener(event -> handleEvent("seriesShow", event));

        add(chart, eventLog);
    }

    private void handleEvent(String eventName, HasSeries event) {
        try {
            Series series = event.getSeries();
            appendLog("OK   " + eventName + " -> " + series);
        } catch (Exception exception) {
            appendLog("FAIL " + eventName + " -> " + exception);
            exception.printStackTrace();
        }
    }

    private void appendLog(String line) {
        eventLog.setText(eventLog.getText() + line + "\n");
    }
}
```
</details>

### Exception

```
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
    at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
    at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
    at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
    at java.base/java.util.Objects.checkIndex(Objects.java:385)
    at java.base/java.util.ArrayList.get(ArrayList.java:427)
    at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1501)
    at com.vaadin.flow.component.charts.events.HasSeries.getSeries(HasSeries.java:39)
    at org.vaadin.example.CandlestickHasSeriesView.handleEvent(CandlestickHasSeriesView.java:89)
    at org.vaadin.example.CandlestickHasSeriesView.lambda$0(CandlestickHasSeriesView.java:77)
    at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:244)
    at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:496)
    ...
```

**Comment by paodb** [comment]
### Workaround

Check `getSeriesItemIndex()` before calling `getSeries()` and ignore events whose index doesn't exist in the server-side configuration (i.e. the navigator series). Tested in 25.3.0 with the reproduction above: with this check the exception no longer occurs and the navigator series event is ignored.

Replace `handleEvent` in the reproduction with the following (and add `java.util.List` and `java.util.Optional` imports):

```java
private void handleEvent(String eventName, HasSeries event) {
    Optional<Series> series = getSeriesSafely(event);
    if (series.isPresent()) {
        appendLog("OK      " + eventName + " -> " + series.get());
    } else {
        // Event from the navigator series: ignored instead of throwing
        appendLog("IGNORED " + eventName + " -> seriesItemIndex=" + event.getSeriesItemIndex());
    }
}

private static Optional<Series> getSeriesSafely(HasSeries event) {
    List<Series> configuredSeries = event.getSource().getConfiguration().getSeries();
    int seriesIndex = event.getSeriesItemIndex();
    // Events coming from the navigator series have an index that doesn't exist
    // in the server-side configuration, so they are ignored
    if (seriesIndex < 0 || seriesIndex >= configuredSeries.size()) {
        return Optional.empty();
    }
    return Optional.of(configuredSeries.get(seriesIndex));
}
```

Result on chart load:

```
OK      afterAnimate -> ...
IGNORED afterAnimate -> seriesItemIndex=1
```
