### ISSUE TITLE
Upload not possible when HTTP2 enabled with Tomcat causes java.io.IOException: java.lang.InterruptedException - Application freezes

### ISSUE THREAD

**Issue by masbaehr** [vaadin/flow-components#1543]
I noticed this exception when using HTTP2 enabled on Tomcat. It does not happen when i disable HTTP2 via Spring setting.  (server.http2.enabled=<true|false>).
The upload sample was a simple JPG image.
I'm not really sure if this is something for upload or flow since the last call was in ServerRpcHandler .. but currently i only encountered this issue when doing an upload - Everything else seems to work, so i posted it here.

```java
java.io.IOException: java.lang.InterruptedException
        at org.apache.coyote.http2.Stream$StreamInputBuffer.doRead(Stream.java:958) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.coyote.Request.doRead(Request.java:551) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:318) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.connector.InputBuffer.realReadChars(InputBuffer.java:387) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.connector.InputBuffer.checkCharBufferEof(InputBuffer.java:621) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:448) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.connector.CoyoteReader.read(CoyoteReader.java:101) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at com.vaadin.flow.server.communication.ServerRpcHandler.getMessage(ServerRpcHandler.java:394) ~[flow-server-1.2.3.jar!/:1.2.3]
        at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:239) ~[flow-server-1.2.3.jar!/:1.2.3]
        at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89) ~[flow-server-1.2.3.jar!/:1.2.3]
        at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-1.2.3.jar!/:1.2.3]
        at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1533) ~[flow-server-1.2.3.jar!/:1.2.3]
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:227) ~[flow-server-1.2.3.jar!/:1.2.3]
        at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:65) ~[vaadin-spring-10.1.1.jar!/:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar!/:4.0.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) ~[spring-webmvc-5.1.3.REL
```

**Comment by web-padawan** [comment]
Closing in favor of https://github.com/vaadin/flow/issues/9492 which has some more information and a link to Tomcat issue.
