### ISSUE TITLE
NPE when no items and data provider set for Crud

### ISSUE THREAD

**Issue by johannesh2** [vaadin/flow-components#1563]
I got 
`java.lang.NullPointerException: null
	at com.vaadin.flow.component.crud.Crud.lambda$registerHandlers$9b1b5227$4(Crud.java:199) ~[vaadin-crud-flow-1.0.1.jar:na]
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:205) ~[flow-server-1.2.0.jar:1.2.0]
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:373) ~[flow-server-1.2.0.jar:1.2.0]
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:264) ~[flow-server-1.2.0.jar:1.2.0]
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:396) ~[flow-server-1.2.0.jar:1.2.0]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_181]`

I had a Crud created for my entity and it was empty. Creating a new item and clicking save throws NPE. Maybe something nicer instead would be in order.

**Comment by TatuLund** [comment]
This will be probably fixed when Enhanced Crud features are cherry picked to Crud product. The root cause is that new event does not return a new bean, which ahs been fixed in Enhanced Crud 

https://github.com/vaadin-component-factory/enhanced-crud/commit/1a8114b66671f95c202cf3bc5171367430ab0560#diff-f4109553cbd1f11a07875e248922a6197d2a44983d1dc39620fe954f08c2e64b

**Comment by web-padawan** [comment]
The `NewEvent` fix mentioned above was ported as part of https://github.com/vaadin/flow-components/pull/2034. Closing, please comment if the issue is still valid.
