### ISSUE TITLE
Grid throws UnsupportedOperationException if buffered editor is open

### ISSUE THREAD

**Issue by robert-lee-hisl** [vaadin/flow-components#1623]
Exception stacktrace begins:

```
ERROR [com.vaadin.flow.server.DefaultErrorHandler] (default task-19) : java.lang.UnsupportedOperationException: Buffered editor should be closed using save() or cancel()
        at com.vaadin.flow.component.grid.editor.EditorImpl.closeEditor(EditorImpl.java:124)
        at com.vaadin.flow.component.grid.Grid.onDataProviderChange(Grid.java:3382)
        at com.vaadin.flow.component.grid.Grid.lambda$handleDataProviderChange$78e8296$1(Grid.java:3425)
```

I saw this when calling refreshItem() on TreeGrid after adding a child item; refreshItem() seems to fire a dataprovider event and no check is done to see if the editor is buffered or not. 

IMHO, the editor should cancel instead of saving in this case, because saving might fail due to validation.

**Comment by TatuLund** [comment]
This is fixed by https://github.com/vaadin/flow-components/pull/865

**Comment by robert-lee-hisl** [comment]
#865 appears to affect padob's use case, but the original issue was about programatically updating the grid's contents, not refreshing the page.

**Comment by web-padawan** [comment]
Could not reproduce using the latest Vaadin version. Closing as stale, please create a new issue if the problem is still relevant.
