### ISSUE TITLE
grid tests fail in latest java JDK16 

### ISSUE THREAD

**Issue by manolo** [vaadin/flow-components#1835]
When running grid tests with JDK16 `TreeGridHugeTreeIT` fails with the following error:

```
# WARNING: Unable to get Instrumentation. Dynamic Attach failed: null. You may add this JAR as -javaagent manually.
# WARNING: Unable to attach Serviceability Agent. Couldn't find PID of current JVM process.
ERROR com.vaadin.flow.router.InternalServerError - There was an exception while trying to navigate to 'vaadin-grid/tree-grid-memory/items=200&initiallyExpanded'
java.lang.UnsupportedOperationException: can't get field offset on a hidden class: private final java.util.Collection com.vaadin.flow.shared.Registration$$Lambda$305/0x0000000801148870.arg$1
	at jdk.unsupported/sun.misc.Unsafe.objectFieldOffset(Unsafe.java:645)
	at org.openjdk.jol.vm.HotspotUnsafe.fieldOffset(HotspotUnsafe.java:412)
	at org.openjdk.jol.info.FieldData.parse(FieldData.java:62)
	at org.openjdk.jol.info.ClassData.parse(ClassData.java:110)
	at org.openjdk.jol.info.ClassData.parseInstance(ClassData.java:53)
	at org.openjdk.jol.vm.HotspotUnsafe.sizeOf(HotspotUnsafe.java:183)
	at org.openjdk.jol.info.GraphPathRecord.<init>(GraphPathRecord.java:60)
	at org.openjdk.jol.info.GraphPathRecord.<init>(GraphPathRecord.java:45)
	at org.openjdk.jol.info.GraphWalker.peelReferences(GraphWalker.java:122)
	at org.openjdk.jol.info.GraphWalker.walk(GraphWalker.java:77)
	at org.openjdk.jol.info.GraphLayout.parseInstance(GraphLayout.java:56)
	at com.vaadin.flow.data.performance.AbstractBeansMemoryTest.setData(AbstractBeansMemoryTest.java:138)
```

**Comment by manolo** [comment]
Note, 1836 is not a fix for the test, just ignores it in JDK16+ so as we can continue testing the project

**Comment by vlukashov** [comment]
Users are not affected hence this issue is not a blocker.

**Comment by web-padawan** [comment]
Closing as no longer relevant.
