### ISSUE TITLE
Console shows error when refreshing items if an item is selected

### ISSUE THREAD

**Issue by mperktold** [vaadin/flow-components#1913]
### Description

When refreshing grid items while an item is selected, the console shows error logs indicating a ReferenceError because of row elements without a corresponding item.

### Expected outcome

The grid should be refreshed, keeping the selection, without any error logs showing in the console.

### Actual outcome

On the surface, everything seems to work properly, but there are error logs:

```
There seems to be an error in the Vaadin Grid:
Cannot read property 'style' of undefined
Please submit an issue to https://github.com/vaadin/vaadin-grid/issues/new!
```

This comes from `tryCatchWrapper` due to an error. Here is the stack trace of the error:

```
"TypeError: Cannot read property 'style' of undefined
    at HTMLElement.eval (webpack-internal:///../target/flow-frontend/gridConnector.js:1014:38)
    at HTMLElement.eval (webpack-internal:///../target/flow-frontend/FlowBootstrap.js:66:41)
    at eval (webpack-internal:///../node_modules/.pnpm/@vaadin/vaadin-grid@20.0.0/node_modules/@vaadin/vaadin-grid/src/vaadin-grid-styling-mixin.js:65:31)
    at Array.forEach (<anonymous>)
    at HTMLElement._generateCellClassNames (webpack-internal:///../node_modules/.pnpm/@vaadin/vaadin-grid@20.0.0/node_modules/@vaadin/vaadin-grid/src/vaadin-grid-styling-mixin.js:60:32)
    at HTMLElement._updateItem (webpack-internal:///../node_modules/.pnpm/@vaadin/vaadin-grid@20.0.0/node_modules/@vaadin/vaadin-grid/src/vaadin-grid.js:841:10)
    at HTMLElement.eval (webpack-internal:///../target/flow-frontend/gridConnector.js:442:114)
    at HTMLElement.eval [as _updateItem] (webpack-internal:///../target/flow-frontend/FlowBootstrap.js:66:41)
    at eval (webpack-internal:///../node_modules/.pnpm/@vaadin/vaadin-grid@20.0.0/node_modules/@vaadin/vaadin-grid/src/vaadin-grid-selection-mixin.js:85:16)
    at Array.forEach (<anonymous>)
    at HTMLElement._selectedItemsChanged (webpack-internal:///../node_modules/.pnpm/@vaadin/vaadin-grid@20.0.0/node_modules/@vaadin/vaadin-grid/src/vaadin-grid-selection-mixin.js:84:43)
    at Object.runMethodEffect [as fn] (webpack-internal:///../node_modules/.pnpm/@polymer/polymer@3.2.0/node_modules/@polymer/polymer/lib/mixins/property-effects.js:829:15)
    at runEffectsForProperty (webpack-internal:///../node_modules/.pnpm/@polymer/polymer@3.2.0/node_modules/@polymer/polymer/lib/mixins/property-effects.js:167:12)
    at runEffects (webpack-internal:///../node_modules/.pnpm/@polymer/polymer@3.2.0/node_modules/@polymer/polymer/lib/mixins/property-effects.js:131:11)
    at HTMLElement._propertiesChanged (webpack-internal:///../node_modules/.pnpm/@polymer/polymer@3.2.0/node_modules/@polymer/polymer/lib/mixins/property-effects.js:1702:7)
    at HTMLElement.Jw.s._propertiesChanged (webpack-internal:///../target/flow-frontend/FlowClient.js:1003:26284)
    at HTMLElement._flushProperties (webpack-internal:///../node_modules/.pnpm/@polymer/polymer@3.2.0/node_modules/@polymer/polymer/lib/mixins/properties-changed.js:360:14)
    at HTMLElement._flushProperties (webpack-internal:///../node_modules/.pnpm/@polymer/polymer@3.2.0/node_modules/@polymer/polymer/lib/mixins/property-effects.js:1546:13)
    at HTMLElement._invalidateProperties (webpack-internal:///../node_modules/.pnpm/@polymer/polymer@3.2.0/node_modules/@polymer/polymer/lib/mixins/property-effects.js:1516:14)
    at HTMLElement._setProperty (webpack-internal:///../node_modules/.pnpm/@polymer/polymer@3.2.0/node_modules/@polymer/polymer/lib/mixins/property-effects.js:1501:14)
    at HTMLElement.Object.defineProperty.set (webpack-internal:///../node_modules/.pnpm/@polymer/polymer@3.2.0/node_modules/@polymer/polymer/lib/mixins/properties-changed.js:159:16)
    at Object.eval (webpack-internal:///../target/flow-frontend/gridConnector.js:208:28)
    at Object.eval [as doDeselection] (webpack-internal:///../target/flow-frontend/FlowBootstrap.js:66:41)
    at Object.eval (webpack-internal:///../target/flow-frontend/gridConnector.js:731:27)
    at Object.eval [as clear] (webpack-internal:///../target/flow-frontend/FlowBootstrap.js:66:41)
    at Object.eval (eval at ot (webpack-internal:///../target/flow-frontend/FlowClient.js), <anonymous>:3:22)
    at ot (webpack-internal:///../target/flow-frontend/FlowClient.js:995:164)
    at nt (webpack-internal:///../target/flow-frontend/FlowClient.js:948:276)
    at lt (webpack-internal:///../target/flow-frontend/FlowClient.js:569:57)
    at Tq (webpack-internal:///../target/flow-frontend/FlowClient.js:498:18)
    at pr.qr [as db] (webpack-internal:///../target/flow-frontend/FlowClient.js:1003:19986)
    at PA (webpack-internal:///../target/flow-frontend/FlowClient.js:918:221)
    at Vq (webpack-internal:///../target/flow-frontend/FlowClient.js:999:303)
    at jr.kr [as F] (webpack-internal:///../target/flow-frontend/FlowClient.js:1003:19656)
    at lk (webpack-internal:///../target/flow-frontend/FlowClient.js:415:29)
    at Nq (webpack-internal:///../target/flow-frontend/FlowClient.js:1001:991)
    at Oq (webpack-internal:///../target/flow-frontend/FlowClient.js:982:401)
    at _s.bt [as yb] (webpack-internal:///../target/flow-frontend/FlowClient.js:1003:23103)
    at sB.tB [as L] (webpack-internal:///../target/flow-frontend/FlowClient.js:1003:35969)
    at XMLHttpRequest.eval (webpack-internal:///../target/flow-frontend/FlowClient.js:579:63)
    at sb (webpack-internal:///../target/flow-frontend/FlowClient.js:425:29)
    at vb (webpack-internal:///../target/flow-frontend/FlowClient.js:869:56)
    at XMLHttpRequest.eval (webpack-internal:///../target/flow-frontend/FlowClient.js:600:46)"
```

### Minimal reproducible example

```java
@Route("")
public class SelectIssue extends VerticalLayout {

    public SelectIssue() {
        Grid<Integer> grid = new Grid<>();
        grid.setSelectionMode(Grid.SelectionMode.SINGLE);
        grid.addColumn(String::valueOf);
        ListDataView<Integer, ?> dataView = grid.setItems(1, 2, 3);

        add(
            new Button("Add", e -> dataView.addItem(dataView.getItemCount() + 1)),
            grid
        );
    }
}
```

### Steps to reproduce

1. Put a `Grid` component in the page.
2. Select an item.
3. Add an item.
4. refreshAll().

### Environment

- v20.0.4
- Windows 10, 64 bit

### Browsers Affected
(All tested browsers are affected)
- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [x] IE 11
- [x] iOS Safari
- [ ] Android Chrome

**Comment by alvarezguille** [comment]
May be related to https://github.com/vaadin/web-components/issues/2247

**Comment by mperktold** [comment]
Indeed, seems to be the same error.

**Comment by xdenser** [comment]
I also have the same problem.
The direct fix is simple: just check that "item" is set on this line and that's it 
https://github.com/vaadin/flow-components/blob/40dfc3a6ea496544ae02416114f8627279a14e16/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js#L1040

why it comes with undefined "item" is another question.

**Comment by xdenser** [comment]
I want to escalate this issue, as we still get this error with v.22.0.2.
It appears when there are selected rows in grid and we insert new row. 
And server calls 'clear' method in 'gridConnector' which triggers grid update and at this point somehow grid elaready has new row  element, but data model (_item property) is missing in this new row - this leads to error.

**Comment by web-padawan** [comment]
Hi @xdenser, could you please provide a code example to reproduce this so we could take a look?

**Comment by xdenser** [comment]
Here is example - actually the code is the same as in initial post.
[gridSelectAndAppendBug.zip](https://github.com/vaadin/flow-components/files/7914918/gridSelectAndAppendBug.zip)
