### ISSUE TITLE
Reattaching a Grid tries to "detach an element from parent that does not have it"

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow-components#2027]
### Description

Consider the following case:
```
  Map<String, Component> map = new HashMap<>();
  Grid<String> grid = new Grid<>();
  grid.setItems("1","2","3");
    
  grid.addComponentColumn(x->map.computeIfAbsent(x, _key -> new Span(x)));

  add(new Button("Attach", ev->add(grid)));    
  add(new Button("Detach", ev->remove(grid)));
```

When clicking on "Attach" for the second time (Attach -> Detach -> Attach), the application fails with the following exception:

```
java.lang.IllegalArgumentException: Trying to detach an element from parent that does not have it.
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.removeChild(AbstractNodeStateProvider.java:125) ~[flow-server-2.6.7.jar:2.6.7]
	at com.vaadin.flow.dom.Node.removeChild(Node.java:376) ~[flow-server-2.6.7.jar:2.6.7]
	at com.vaadin.flow.dom.Element.removeFromParent(Element.java:578) ~[flow-server-2.6.7.jar:2.6.7]
	at com.vaadin.flow.dom.Node.insertChild(Node.java:293) ~[flow-server-2.6.7.jar:2.6.7]
	at com.vaadin.flow.dom.Node.appendChild(Node.java:141) ~[flow-server-2.6.7.jar:2.6.7]
	at com.vaadin.flow.data.provider.AbstractComponentDataGenerator.registerRenderedComponent(AbstractComponentDataGenerator.java:131) ~[flow-data-2.6.7.jar:2.6.7]
	at com.vaadin.flow.data.provider.ComponentDataGenerator.generateData(ComponentDataGenerator.java:93) ~[flow-data-2.6.7.jar:2.6.7]
	at com.vaadin.flow.data.provider.CompositeDataGenerator.lambda$generateData$0(CompositeDataGenerator.java:47) ~[flow-data-2.6.7.jar:2.6.7]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_92]
	at com.vaadin.flow.data.provider.CompositeDataGenerator.generateData(CompositeDataGenerator.java:47) ~[flow-data-2.6.7.jar:2.6.7]
	at com.vaadin.flow.data.provider.DataCommunicator.generateJson(DataCommunicator.java:665) ~[flow-data-2.6.7.jar:2.6.7]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_92]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_92]
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250) ~[na:1.8.0_92]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) ~[na:1.8.0_92]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693) ~[na:1.8.0_92]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_92]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_92]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_92]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_92]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_92]
	at com.vaadin.flow.data.provider.DataCommunicator.getJsonItems(DataCommunicator.java:622) ~[flow-data-2.6.7.jar:2.6.7]
	at com.vaadin.flow.data.provider.DataCommunicator.collectChangesToSend(DataCommunicator.java:560) ~[flow-data-2.6.7.jar:2.6.7]
	at com.vaadin.flow.data.provider.DataCommunicator.flush(DataCommunicator.java:477) ~[flow-data-2.6.7.jar:2.6.7]
	at com.vaadin.flow.data.provider.DataCommunicator.lambda$requestFlush$2f364bb9$1(DataCommunicator.java:425) ~[flow-data-2.6.7.jar:2.6.7]
	at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$2(StateTree.java:392) ~[flow-server-2.6.7.jar:2.6.7]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_92]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_92]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_92]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_92]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_92]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_92]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_92]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_92]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_92]
	at com.vaadin.flow.internal.StateTree.runExecutionsBeforeClientResponse(StateTree.java:389) ~[flow-server-2.6.7.jar:2.6.7]
	at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:413) ~[flow-server-2.6.7.jar:2.6.7]
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:189) ~[flow-server-2.6.7.jar:2.6.7]
	at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124) ~[flow-server-2.6.7.jar:2.6.7]
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:93) ~[flow-server-2.6.7.jar:2.6.7]
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-2.6.7.jar:2.6.7]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1570) ~[flow-server-2.6.7.jar:2.6.7]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:252) [flow-server-2.6.7.jar:2.6.7]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:111) [vaadin-spring-12.4.0.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) [spring-webmvc-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177) [spring-webmvc-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52) [spring-webmvc-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) [spring-webmvc-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) [spring-webmvc-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.27.jar:9.0.27]
```

### Expected outcome

No exception should be thrown. 

### Actual outcome

An exception is thrown.

### Minimal reproducible example
See above

### Steps to reproduce

1. Click "Attach"
2. Click "Detach"
3. Click "Attach"

### Workaround

- Initialize the grid on attach and remove all columns after the grid is detached
- Explicitly detach all components _before_ detaching the grid (detaching them in the detach listener is too late)

```
    Map<String, Component> map = new HashMap<>();
    Grid<String>  grid = new Grid<>();
    grid.setItems("1","2","3");
    
    grid.addAttachListener(ev->{
      //initialize the grid on attach
      grid.addComponentColumn(x->map.computeIfAbsent(x, _key -> new Span(x)));
    });
    grid.addDetachListener(ev->{
      //remove all columns after the grid is detached
      grid.removeAllColumns();
    });
    
    add(new Button("Attach 1", ev->add(grid)));
    
    add(new Button("Detach 1", ev->{
      //explicitly detach all the components before detaching the grid 
      map.values().forEach(c->c.getElement().removeFromParent());
      remove(grid);
    }));
```

### Environment

- Vaadin 14.6.8

**Comment by TatuLund** [comment]
The code example recycles component instanced cached in the map, this is not supported in the Grid, as the callback in the addComponentColumn must allways return a new instance of the component. 

See also: https://github.com/vaadin/flow/issues/7143#issuecomment-565385615
