### ISSUE TITLE
HorizontalLayout.setVerticalComponentAlignment should check that given components are child components

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow-components#2183]
### Description
Calling e.g. `HorizontalLayout.setVerticalComponentAlignment` on a component that is not a child of the layout results in

```
Caused by: java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.component.HasElement.getElement()" because "container" is null
	at com.vaadin.flow.component.orderedlayout.FlexComponent.setAlignSelf(FlexComponent.java:205) ~[vaadin-ordered-layout-flow-22.0-SNAPSHOT.jar:na]
	at com.vaadin.flow.component.orderedlayout.HorizontalLayout.setAlignSelf(HorizontalLayout.java:197) ~[vaadin-ordered-layout-flow-22.0-SNAPSHOT.jar:na]
	at com.vaadin.flow.component.orderedlayout.HorizontalLayout.setVerticalComponentAlignment(HorizontalLayout.java:93) ~[vaadin-ordered-layout-flow-22.0-SNAPSHOT.jar:na]
	at com.example.application.views.helloworld.HelloWorldView.<init>(HelloWorldView.java:24) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
```

### Expected outcome

A warning that the component is not a child of the layout or an exception describing that

### Actual outcome

A stack trace you need to read 5 times to realize what is wrong

### Minimal reproducible example

```
@Route(value = """)
public class HelloWorldView extends HorizontalLayout {

    public HelloWorldView() {
        sayHello = new Button("A button");
        setVerticalComponentAlignment(Alignment.END, sayHello);

    }




### Environment

- Version of the component / Vaadin platform. 22 alpha 6

**Comment by yuriy-fix** [comment]
Should probably throw InvalidArgument exception.

**Comment by tomivirkki** [comment]
Just tested with the following view, no exceptions are thrown:

```java
@Route(value = "hello")
public class HelloWorldView extends HorizontalLayout {

    private Button sayHello;

    public HelloWorldView() {
        sayHello = new Button("A button");
        setVerticalComponentAlignment(Alignment.END, sayHello);
    }
}
```

It's still possible to add logic to throw an `IllegalArgumentException` if we don't want to support the following (which works now):
```java
sayHello = new Button("A button");
// Set alignment _before_ the component is added
setVerticalComponentAlignment(Alignment.END, sayHello);
add(sayHello);
```
