### ISSUE TITLE
Creating grid with more than 7 footers throws JS exception

### ISSUE THREAD

**Issue by komitoff** [vaadin/flow-components#2565]
Hello there, 
We are migrating our application from vaadin 8 to vaadin 14. We have a very complex grid with a lot of dynamic footers based on different conditions. I created a simpler demo, so it will be easier for you to see the problem. 
I have a grid with several columns and a bunch of footers

![footer_error](https://user-images.githubusercontent.com/7748256/151111670-7fa486a2-da9f-447f-9693-5938d6f2c5d6.png)

When I start the application, there is an exception in the browser console and seems the order of the columns in the footer is wrong. I've noticed that all the columns in the footer has a property called order=0, but for some of the columns it has order=1111111
![grid_footer_order](https://user-images.githubusercontent.com/7748256/151111687-3fb284fc-082b-40bc-b027-a55af596c958.png)

And here is the JS error I got in the browser console: 
`client-661F308588AD7572265EBD1D8EEA0A19.cache.js:213 TypeError: Cannot read properties of null (reading 'pop')
nD @ client-661F308588AD7572265EBD1D8EEA0A19.cache.js:213
ao @ client-661F308588AD7572265EBD1D8EEA0A19.cache.js:1016
_n @ client-661F308588AD7572265EBD1D8EEA0A19.cache.js:787
bo @ client-661F308588AD7572265EBD1D8EEA0A19.cache.js:607
lj @ client-661F308588AD7572265EBD1D8EEA0A19.cache.js:1037
Ab @ client-661F308588AD7572265EBD1D8EEA0A19.cache.js:795
h @ client-661F308588AD7572265EBD1D8EEA0A19.cache.js:963
a.onerror @ client-661F308588AD7572265EBD1D8EEA0A19.cache.js:964
async.js?1bee:41 Uncaught TypeError: Cannot read properties of null (reading 'pop')
    at GridColumnGroupElement._groupOrderChanged (vaadin-grid-column-group.js?d855:153:1)
    at Object.runMethodEffect [as fn] (property-effects.js?0662:819:1)
    at runEffectsForProperty (property-effects.js?0662:157:1)
    at runEffects (property-effects.js?0662:121:1)
    at GridColumnGroupElement._propertiesChanged (property-effects.js?0662:1692:1)
    at GridColumnGroupElement.Dx.s._propertiesChanged (client-661F308588AD7572265EBD1D8EEA0A19.cache.js:1037:27384)
    at GridColumnGroupElement._flushProperties (properties-changed.js?2b39:354:1)
    at GridColumnGroupElement._flushProperties (property-effects.js?0662:1536:1)
    at GridColumnGroupElement._invalidateProperties (property-effects.js?0662:1506:1)
    at GridColumnGroupElement._setProperty (property-effects.js?0662:1491:1)
    at GridColumnGroupElement.Object.defineProperty.set (properties-changed.js?2b39:153:1)
    at eval (vaadin-grid-helpers.js?5eb7:22:1)
    at Array.forEach (<anonymous>)
    at Function._updateColumnOrders (vaadin-grid-helpers.js?5eb7:16:1)
    at GridColumnGroupElement._groupOrderChanged (vaadin-grid-column-group.js?d855:167:1)
    at Object.runMethodEffect [as fn] (property-effects.js?0662:819:1)
    at runEffectsForProperty (property-effects.js?0662:157:1)
    at runEffects (property-effects.js?0662:121:1)
    at GridColumnGroupElement._propertiesChanged (property-effects.js?0662:1692:1)
    at GridColumnGroupElement.Dx.s._propertiesChanged (client-661F308588AD7572265EBD1D8EEA0A19.cache.js:1037:27384)
    at GridColumnGroupElement._flushProperties (properties-changed.js?2b39:354:1)
    at GridColumnGroupElement._flushProperties (property-effects.js?0662:1536:1)
    at GridColumnGroupElement._invalidateProperties (property-effects.js?0662:1506:1)
    at GridColumnGroupElement._setProperty (property-effects.js?0662:1491:1)
    at GridColumnGroupElement.Object.defineProperty.set (properties-changed.js?2b39:153:1)
    at eval (vaadin-grid-helpers.js?5eb7:22:1)
    at Array.forEach (<anonymous>)
    at Function._updateColumnOrders (vaadin-grid-helpers.js?5eb7:16:1)
    at GridColumnGroupElement._groupOrderChanged (vaadin-grid-column-group.js?d855:167:1)
    at Object.runMethodEffect [as fn] (property-effects.js?0662:819:1)
    at runEffectsForProperty (property-effects.js?0662:157:1)
    at runEffects (property-effects.js?0662:121:1)
    at GridColumnGroupElement._propertiesChanged (property-effects.js?0662:1692:1)
    at GridColumnGroupElement.Dx.s._propertiesChanged (client-661F308588AD7572265EBD1D8EEA0A19.cache.js:1037:27384)
    at GridColumnGroupElement._flushProperties (properties-changed.js?2b39:354:1)
    at GridColumnGroupElement._flushProperties (property-effects.js?0662:1536:1)
    at GridColumnGroupElement._invalidateProperties (property-effects.js?0662:1506:1)
    at GridColumnGroupElement._setProperty (property-effects.js?0662:1491:1)
    at GridColumnGroupElement.Object.defineProperty.set (properties-changed.js?2b39:153:1)
    at eval (vaadin-grid-helpers.js?5eb7:22:1)
    at Array.forEach (<anonymous>)
    at Function._updateColumnOrders (vaadin-grid-helpers.js?5eb7:16:1)
    at GridColumnGroupElement._groupOrderChanged (vaadin-grid-column-group.js?d855:167:1)
    at Object.runMethodEffect [as fn] (property-effects.js?0662:819:1)
    at runEffectsForProperty (property-effects.js?0662:157:1)
    at runEffects (property-effects.js?0662:121:1)
    at GridColumnGroupElement._propertiesChanged (property-effects.js?0662:1692:1)
    at GridColumnGroupElement.Dx.s._propertiesChanged (client-661F308588AD7572265EBD1D8EEA0A19.cache.js:1037:27384)
    at GridColumnGroupElement._flushProperties (properties-changed.js?2b39:354:1)
    at GridColumnGroupElement._flushProperties (property-effects.js?0662:1536:1)
    at GridColumnGroupElement._invalidateProperties (property-effects.js?0662:1506:1)
    at GridColumnGroupElement._setProperty (property-effects.js?0662:1491:1)
    at GridColumnGroupElement.Object.defineProperty.set (properties-changed.js?2b39:153:1)
    at eval (vaadin-grid-helpers.js?5eb7:22:1)
    at Array.forEach (<anonymous>)
    at Function._updateColumnOrders (vaadin-grid-helpers.js?5eb7:16:1)
    at GridColumnGroupElement._groupOrderChanged (vaadin-grid-column-group.js?d855:167:1)
    at Object.runMethodEffect [as fn] (property-effects.js?0662:819:1)
    at runEffectsForProperty (property-effects.js?0662:157:1)
    at runEffects (property-effects.js?0662:121:1)
    at GridColumnGroupElement._propertiesChanged (property-effects.js?0662:1692:1)
    at GridColumnGroupElement.Dx.s._propertiesChanged (client-661F308588AD7572265EBD1D8EEA0A19.cache.js:1037:27384)
    at GridColumnGroupElement._flushProperties (properties-changed.js?2b39:354:1)
    at GridColumnGroupElement._flushProperties (property-effects.js?0662:1536:1)`
    
One side node, is it possible to style the footers based on some conditions different than their order. For example - lets say I want 3 of them to be red, 4 to be blue and so on (the conditions are part of our application logic and they can be changed based on user selection in different components). 

Thanks in advance !

**Comment by tomivirkki** [comment]
Hi @komitoff 
There is a [hard-coded maximum](https://github.com/vaadin/web-components/blob/5e0b6e30daec0d4c44156f2cd860d6a04413c732/packages/grid/src/vaadin-grid-column-reordering-mixin.js#L29) for how many column levels the grid supports. This is the first time I hear the default maximum isn't enough.

The root level column group gets the order value of 10000000 and the number cascades down to child columns as described [here](https://github.com/vaadin/web-components/blob/5e0b6e30daec0d4c44156f2cd860d6a04413c732/packages/grid/src/vaadin-grid-column-group.js#L149-L153). The number is used for flex-box (re-)ordering of the row cells.


You can workaround the issue by increasing the maximum with:

```java
Grid<Person> grid = new Grid<>();
int NUMBER_OF_COLUMN_LEVELS = 15;
grid.getElement().setProperty("_orderBaseScope", Math.pow(10, NUMBER_OF_COLUMN_LEVELS));
```

**Comment by web-padawan** [comment]
Duplicate of vaadin/web-components#1476

**Comment by komitoff** [comment]
Hi @tomivirkki. 
The workaround you suggested seems to work. Thanks for your help
