### ISSUE TITLE
CrudGrid.setItems throws IllegalStateException 

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow-components#3050]
### Description

The following code fails with IllegalStateException:
```
CrudGrid<Bean> grid = new CrudGrid<>(Bean.class, true);
grid.setItems(new Bean());
```

```		
java.lang.IllegalStateException: GridListDataView only supports 'ListDataProvider' or it's subclasses, but was given a 'ConfigurableFilterDataProviderWrapper'.
Use either 'getLazyDataView()', 'getListDataView()' or 'getGenericDataView()' according to the used data type.
	at com.vaadin.flow.data.provider.AbstractDataView.verifyDataProviderType(AbstractDataView.java:114)
	at com.vaadin.flow.data.provider.AbstractDataView.<init>(AbstractDataView.java:74)
	at com.vaadin.flow.data.provider.AbstractListDataView.<init>(AbstractListDataView.java:71)
	at com.vaadin.flow.component.grid.dataview.GridListDataView.<init>(GridListDataView.java:53)
	at com.vaadin.flow.component.grid.Grid.getListDataView(Grid.java:2467)
	at com.vaadin.flow.component.grid.Grid.setItems(Grid.java:2449)
	at com.vaadin.flow.component.grid.Grid.setItems(Grid.java:143)
	at com.vaadin.flow.data.provider.HasListDataView.setItems(HasListDataView.java:66)
```

### Expected outcome

`setItems` should work (if it's not possible to support `setItems` in `CrudGrid` it should be deprecated).  

### Minimal reproducible example

```java
CrudGrid<Bean> grid = new CrudGrid<>(Bean.class, true);
grid.setItems(new Bean());
```

### Steps to reproduce

1. Add the snippet above to a view
2. Navigate to that view: the exception is thrown.

### Environment

Vaadin version(s): 23.0.6

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment]
> [!WARNING]
> **Automated reproduction — produced by the Claude Code `repro` skill. Needs human verification.**
> The steps, verdict, and root-cause pointer below were generated automatically and must be confirmed by a human before being treated as authoritative.

- **Verdict:** not reproduced (fixed)
- **Hypothesis tested:** The bug is an `IllegalStateException` from `getListDataView`/`verifyDataProviderType`, triggered by `CrudGrid.setItems(...)` (CrudGrid wraps its data provider in a `ConfigurableFilterDataProvider`, which the ListDataView type check rejected), observable as the exception thrown on view construction.
- **Regression?:** not a regression — broken since the DataView API was introduced; fixed in Flow 24.4
- **Fixed by:** [vaadin/flow#18317](https://github.com/vaadin/flow/pull/18317) — "feat: support DataProviderWrapper better in AbstractDataView" (commit `cdfde35852`, merged 2023-12-15, Flow 24.4). Added `DataProviderWrapper.getWrappedDataProvider()` and made `AbstractDataView.verifyDataProviderType` re-check the wrapped provider instead of throwing.
- **Duplicate of:** none found
- **Branch:** none pushed (not reproduced)
- **Reproduced on:** flow-components @ `main` (34b386bf39) with flow core @ `1ac6a6e4b1` — attempted, did **not** reproduce
- **Present on main?:** no
- **Theme / Browser:** Lumo / Chromium (playwright-cli); the failure was server-side, not browser related
- **Screenshot:** local only — `scratchpad/repro-3050.png` (both calls report "OK")

## Observed behavior

A view running the reporter's exact snippet plus a plain-`Grid` control, each wrapped in try/catch and reporting to a span:

- **`CrudGrid.setItems(new Person(...))`** → `CrudGrid.setItems: OK` — no exception.
- **`Grid.setItems(new Person(...))`** (control) → `Grid.setItems: OK`.
- Server log has zero `IllegalStateException` / `IllegalArgumentException` entries; console shows only dev-mode noise.

## Expected behavior (per reporter)

`setItems` should work (or be deprecated if unsupported). It now works.

## Why it no longer reproduces

`CrudGrid` still wraps whatever provider it is given in a `ConfigurableFilterDataProvider` (a `DataProviderWrapper`), and `setItems` still routes through `getListDataView()` → `verifyDataProviderType(...)`. What changed is the verification: [vaadin/flow#18317](https://github.com/vaadin/flow/pull/18317) (Flow 24.4) added an overload that, when the direct type check fails, checks whether the provider is a `DataProviderWrapper` and re-verifies the **wrapped** provider via the new public `getWrappedDataProvider()`. `CrudGrid` wraps a `ListDataProvider`, so the unwrapped check passes and no exception is thrown.

Chain confirmed: `ConfigurableFilterDataProviderWrapper extends DataProviderWrapper`, so the unwrap branch applies.

## Steps attempted

1. `new CrudGrid<>(Person.class, true).setItems(new Person(1, "John", "Doe"))` in a view, navigated to it.
2. Same call on a plain `Grid<Person>` as a control.

Both succeed.

## Root cause of the fix (Flow core)

Wrapper-aware data-provider verification:

https://github.com/vaadin/flow/blob/1ac6a6e4b156dda1460d63be1fa45b826ef92898/flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java#L133-L147

`CrudGrid` (unchanged) still wraps the provider here:

https://github.com/vaadin/flow-components/blob/34b386bf396519e0f128145955de974e48891547/vaadin-crud-flow-parent/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/CrudGrid.java#L138-L157

## Notes

- Reported against Vaadin 23.0.6 (Flow 23.x). The fix (flow#18317) landed on the Flow 24.4 line, so any 24.4+ Vaadin no longer throws.
- flow#18317 was authored for #18088 (item-index API) and did not reference this issue, which is why #3050 stayed open.
- Recommendation: close as fixed by vaadin/flow#18317 (Flow 24.4+).

**Comment by web-padawan** [comment]
Closing as fixed per above comment.
