### ISSUE TITLE
GridElement.getRow() fails with NPE on non-existing row

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#3111]
### Description

Calling `GridElement.getRow(0)` on an empty Grid fails with a NPE:
```java
java.lang.NullPointerException
	at com.vaadin.flow.component.grid.testbench.GridElement.getRow(GridElement.java:194)
	at com.vaadin.flow.component.grid.testbench.GridElement.select(GridElement.java:343)
```
It should either return null, or even better fail with a more informative exception (e.g. `IndexOutOfBoundsException`)

### Expected outcome

`IndexOutOfBoundsException` should have been thrown

### Minimal reproducible example

```java
public class MainView extends VerticalLayout {

    public MainView() {
        Grid<String> grid = new Grid<String>();
        grid.setItems();
        grid.setId("grid");
        grid.addColumn(it -> it).setHeader("foo");
        add(grid);
    }
}

public class MainViewIT extends AbstractViewTest {
    @Test
    public void myTest() {
        GridElement grid = $(GridElement.class).first();
        grid.select(0);
    }
}
```

### Steps to reproduce

Paste the classes into the "skeleton starter flow" project, then run the IT tests

### Environment

Vaadin version(s): 14.7.5
Reproduced on Firefox, untested on other browsers

### Browsers

Firefox

**Comment by mvysny** [comment]
Workaround:
```java
public class MyGridElement extends GridElement {
    @Override
    public GridTRElement getRow(int rowIndex) {
        if (rowIndex < 0 || rowIndex >= getRowCount()) {
            throw new IndexOutOfBoundsException("rowIndex: expected to be 0.." + (getRowCount() - 1) + " but was " + rowIndex);
        }
        return super.getRow(rowIndex);
    }
}
```
