### ISSUE TITLE
[ComboBox ] ItemLabelGenerator with Binder fails with NPE if child object is null

### ISSUE THREAD

**Issue by khauser** [vaadin/flow-components#3307]
### Description

I have an object booking which has a relation to a rentalProperty. The rentalProperty of a booking could be also null.
When editing a booking I also want to set the rentalProperty via a list of the existing once.

With the added sample code my program fails with the following stacktrace:
```
java.lang.RuntimeException: com.vaadin.flow.data.binder.BindingException: An exception has been thrown inside binding logic for the field element [label='Mietobjekt']
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:229) ~[flow-server-23.0.7.jar:23.0.7]
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:199) ~[flow-server-23.0.7.jar:23.0.7]
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:149) ~[flow-server-23.0.7.jar:23.0.7]
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.handleNode(PublishedServerEventHandlerRpcHandler.java:132) ~[flow-server-23.0.7.jar:23.0.7]
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:76) ~[flow-server-23.0.7.jar:23.0.7]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:438) ~[flow-server-23.0.7.jar:23.0.7]
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$1(ServerRpcHandler.java:419) ~[flow-server-23.0.7.jar:23.0.7]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:419) ~[flow-server-23.0.7.jar:23.0.7]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:320) ~[flow-server-23.0.7.jar:23.0.7]
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:115) ~[flow-server-23.0.7.jar:23.0.7]
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-23.0.7.jar:23.0.7]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1567) ~[flow-server-23.0.7.jar:23.0.7]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:299) ~[flow-server-23.0.7.jar:23.0.7]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:109) ~[vaadin-spring-23.0.7.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.62.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:353) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:313) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) ~[spring-webmvc-5.3.19.jar:5.3.19]
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177) ~[spring-webmvc-5.3.19.jar:5.3.19]
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51) ~[spring-webmvc-5.3.19.jar:5.3.19]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.19.jar:5.3.19]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.19.jar:5.3.19]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.19.jar:5.3.19]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.19.jar:5.3.19]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-embed-core-9.0.62.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.19.jar:5.3.19]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.62.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.19.jar:5.3.19]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.19.jar:5.3.19]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.19.jar:5.3.19]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.19.jar:5.3.19]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.6.7.jar:2.6.7]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.19.jar:5.3.19]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.19.jar:5.3.19]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.19.jar:5.3.19]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: com.vaadin.flow.data.binder.BindingException: An exception has been thrown inside binding logic for the field element [label='Mietobjekt']
	at com.vaadin.flow.data.binder.Binder$BindingImpl.execute(Binder.java:1542) ~[flow-data-23.0.7.jar:23.0.7]
	at com.vaadin.flow.data.binder.Binder$BindingImpl.convertAndSetFieldValue(Binder.java:1438) ~[flow-data-23.0.7.jar:23.0.7]
	at com.vaadin.flow.data.binder.Binder$BindingImpl.lambda$initFieldValue$1(Binder.java:1344) ~[flow-data-23.0.7.jar:23.0.7]
	at com.vaadin.flow.data.binder.Binder$BindingImpl.execute(Binder.java:1532) ~[flow-data-23.0.7.jar:23.0.7]
	at com.vaadin.flow.data.binder.Binder$BindingImpl.initFieldValue(Binder.java:1342) ~[flow-data-23.0.7.jar:23.0.7]
	at com.vaadin.flow.data.binder.Binder.lambda$readBean$2(Binder.java:2115) ~[flow-data-23.0.7.jar:23.0.7]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at com.vaadin.flow.data.binder.Binder.readBean(Binder.java:2107) ~[flow-data-23.0.7.jar:23.0.7]
	at lessoria.ui.views.booking.BookingView.showDetails(BookingView.java:188) ~[main/:na]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
	at lessoria.ui.views.booking.BookingView.lambda$2(BookingView.java:155) ~[main/:na]
	at com.vaadin.flow.component.grid.AbstractGridMultiSelectionModel.lambda$addSelectionListener$c8df87e0$1(AbstractGridMultiSelectionModel.java:276) ~[vaadin-grid-flow-23.0.10.jar:na]
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:206) ~[flow-server-23.0.7.jar:23.0.7]
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:195) ~[flow-server-23.0.7.jar:23.0.7]
	at com.vaadin.flow.component.Component.fireEvent(Component.java:378) ~[flow-server-23.0.7.jar:23.0.7]
	at com.vaadin.flow.component.grid.Grid.access$100(Grid.java:155) ~[vaadin-grid-flow-23.0.10.jar:na]
	at com.vaadin.flow.component.grid.Grid$SelectionMode$2$1.fireSelectionEvent(Grid.java:294) ~[vaadin-grid-flow-23.0.10.jar:na]
	at com.vaadin.flow.component.grid.AbstractGridMultiSelectionModel.selectFromClient(AbstractGridMultiSelectionModel.java:115) ~[vaadin-grid-flow-23.0.10.jar:na]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
	at com.vaadin.flow.component.grid.Grid.select(Grid.java:3132) ~[vaadin-grid-flow-23.0.10.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:222) ~[flow-server-23.0.7.jar:23.0.7]
	... 68 common frames omitted
Caused by: java.lang.IllegalStateException: Got 'null' as a label value for the item 'links: []'. 'ItemLabelGenerator' instance may not return 'null' values
	at com.vaadin.flow.component.combobox.ComboBox.generateLabel(ComboBox.java:1610) ~[vaadin-combo-box-flow-23.0.10.jar:na]
	at com.vaadin.flow.component.combobox.ComboBox.lambda$new$d760694e$1(ComboBox.java:291) ~[vaadin-combo-box-flow-23.0.10.jar:na]
	at com.vaadin.flow.data.provider.CompositeDataGenerator.lambda$generateData$0(CompositeDataGenerator.java:47) ~[flow-data-23.0.7.jar:23.0.7]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at com.vaadin.flow.data.provider.CompositeDataGenerator.generateData(CompositeDataGenerator.java:47) ~[flow-data-23.0.7.jar:23.0.7]
	at com.vaadin.flow.component.combobox.ComboBox.refreshValue(ComboBox.java:419) ~[vaadin-combo-box-flow-23.0.10.jar:na]
	at com.vaadin.flow.component.combobox.ComboBox.setValue(ComboBox.java:397) ~[vaadin-combo-box-flow-23.0.10.jar:na]
	at com.vaadin.flow.data.binder.Binder$BindingImpl.lambda$convertAndSetFieldValue$4(Binder.java:1441) ~[flow-data-23.0.7.jar:23.0.7]
	at com.vaadin.flow.data.binder.Binder$BindingImpl.execute(Binder.java:1532) ~[flow-data-23.0.7.jar:23.0.7]
	... 92 common frames omitted
```

So obviously getShortName couldn't be executed because rentalProperty is null,

### Expected outcome

setItemLabelGenerator shouldn't fail in the described case, instead it should create the ComboBox with it's values but with no one selected.

### Minimal reproducible example

```java
Binder<BookingDTO> binder = new Binder<>(BookingDTO.class);
ComboBox<RentalPropertyDTO> rentalPropertyField = new ComboBox<>("Mietobjekt));
binder.forField(rentalPropertyField).bind(BookingDTO::getRentalProperty, BookingDTO::setRentalProperty);
rentalPropertyField.setItemLabelGenerator(RentalPropertyDTO::getShortName);
List<RentalPropertyDTO> rentalProperties = new ArrayList<>(rentalPropertyFeignClient.findAllByAccountId(contextAccount.getId()).getContent());
rentalPropertyField.setItems(rentalProperties);

binder.readBean(booking);
```

### Steps to reproduce

1. Add the model as described
2. add the code from above
3. start the application and open the browser

### Environment

Vaadin version(s): 23.0.10
OS: Windows 11; jdk 17

### Browsers

Firefox

**Comment by tomivirkki** [comment]
Hi, the failure doesn't happen due to the `rentalProperty` being `null` for the `booking`, but due to one of the rentalProperties passed to the ComboBox as items returning `null` from `getShortName()`.

It's also stated in the stack trace you pasted: `Got 'null' as a label value for the item 'links: []'. 'ItemLabelGenerator' instance may not return 'null' values`.

Please make sure to handle `null` values in your `ItemLabelGenerator`:

```java
rentalPropertyField.setItemLabelGenerator(prop -> {
    if (prop.getShortName() != null) {
        return prop.getShortName();
    } else {
        return "Short name is null";
    }
});
```

**Comment by khauser** [comment]
Indeed rentalProperty was not null but an empty object. Now it's working. Thank you
