### ISSUE TITLE
TreeGrid does not support generic data view.

### ISSUE THREAD

**Issue by simasch** [vaadin/flow-components#3404]
### Description

I use a TreeGrid with a `AbstractBackEndHierarchicalDataProvider`.

setDataprovider is deprecated but when I use `setItems `I get:

```
java.lang.UnsupportedOperationException: TreeGrid does not support generic data view.
	at com.vaadin.flow.component.treegrid.TreeGrid.getGenericDataView(TreeGrid.java:542) ~[vaadin-grid-flow-23.1.1.jar:na]
	at com.vaadin.flow.component.grid.Grid.setItems(Grid.java:2476) ~[vaadin-grid-flow-23.1.1.jar:na]
```

### Expected outcome

Should work as expected.

### Minimal reproducible example

None

### Steps to reproduce

None

### Environment

Vaadin version(s): 23.1.1

### Browsers

Issue is not browser related

**Comment by simasch** [comment]
I'm sorry!!!
For some reason I didn't find my other issue 🤷
