### ISSUE TITLE
Null check for event registration.

### ISSUE THREAD

**Issue by abdullahtellioglu** [vaadin/flow-components#3440]
### Describe your motivation

Users can register null event listeners to components. If null listener is registered and event is triggered application throws 

```
java.lang.NullPointerException: null
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:206) ~[flow-server-23.1.1.jar:23.1.1]
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:448) ~[flow-server-23.1.1.jar:23.1.1]
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:265) ~[flow-server-23.1.1.jar:23.1.1]
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:447) ~[flow-server-23.1.1.jar:23.1.1]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:447) ~[flow-server-23.1.1.jar:23.1.1]
```

This message has no clue about what went wrong. 

### Describe the solution you'd like

If user tries to register a null listener throws exception immediately to ensure that any listener is null.

### Describe alternatives you've considered

Valid stacktrace messages would be fine as well instead of null pointer exception.

**Comment by web-padawan** [comment]
Thanks for the issue. This seems like a bug, so please provide us a code example so that we could reproduce it.

**Comment by abdullahtellioglu** [comment]
Same issue: https://github.com/vaadin/flow/issues/14150 
I am closing this comment!
