### ISSUE TITLE
PiT 23.2: map component is not shown

### ISSUE THREAD

**Issue by manolo** [vaadin/flow-components#3630]
### Description

When using 23.2 map component is not rendered.

There is an exception in server side

```
java.lang.IllegalArgumentException: Unable to create an event object of type com.vaadin.flow.component.map.events.MapViewMoveEndEvent
	at com.vaadin.flow.component.ComponentEventBus.createEventForDomEvent(ComponentEventBus.java:517) ~[flow-server-23.2.0.beta3.jar:23.2.0.beta3]
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:474) ~[flow-server-23.2.0.beta3.jar:23.2.0.beta3]
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:292) ~[flow-server-23.2.0.beta3.jar:23.2.0.beta3]
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:447) ~[flow-server-23.2.0.beta3.jar:23.2.0.beta3
...

Caused by: java.lang.ClassCastException: class elemental.json.impl.JreJsonNull cannot be cast to class elemental.json.JsonNumber (elemental.json.impl.JreJsonNull and elemental.json.JsonNumber are in unnamed module of loader 'app')
	at elemental.json.impl.JreJsonArray.getNumber(JreJsonArray.java:92) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at com.vaadin.flow.component.map.events.MapViewMoveEndEvent.<init>(MapViewMoveEndEvent.java:47) ~[vaadin-map-flow-23.2.0.beta4.jar:na]

```

### Expected outcome

map is rendered correctly

### Minimal reproducible example

```
curl -s -f 'https://start.vaadin.com/dl?&preset=pre-java&projectName=pre-java' -o pre-java.zip
unzip pre-java.zip
cd pre-java
mvn
```

Visit http://localhost:8080/map-view and you can see a white map

![Screenshot 2022-08-30 at 11 50 46](https://user-images.githubusercontent.com/161853/187406980-3e2eecbe-0152-4853-bd4e-2d301e65dae7.png)

### Steps to reproduce

see above

### Environment

Vaadin version(s): 23.0.0.beta4

### Browsers

Issue is not browser related

**Comment by manolo** [comment]
Fixed here https://github.com/vaadin/start/pull/2048 also there is docs noticing this
