### ISSUE TITLE
PiT 23.2: `VaadinSession` not locked in `MapBase`

### ISSUE THREAD

**Issue by manolo** [vaadin/flow-components#3641]
### Description

`MapBase.requestConfigurationSync`  does not lock session when accessing `VaadinSession`, it causes the following exception breaking the UI:

```
Caused by: java.lang.IllegalStateException: Cannot access state in VaadinSession or UI without locking the session.
	at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:578) ~[flow-server-23.2.0.beta3.jar:23.2.0.beta3]
	at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:592) ~[flow-server-23.2.0.beta3.jar:23.2.0.beta3]
	at com.vaadin.flow.internal.StateTree.checkHasLock(StateTree.java:432) ~[flow-server-23.2.0.beta3.jar:23.2.0.beta3]
	at com.vaadin.flow.internal.StateTree.beforeClientResponse(StateTree.java:362) ~[flow-server-23.2.0.beta3.jar:23.2.0.beta3]
	at com.vaadin.flow.component.UI.beforeClientResponse(UI.java:1184) ~[flow-server-23.2.0.beta3.jar:23.2.0.beta3]
	at com.vaadin.flow.component.map.MapBase.lambda$requestConfigurationSync$0(MapBase.java:111) ~[vaadin-map-flow-23.2.0.beta4.jar:na]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
	at com.vaadin.flow.component.map.MapBase.requestConfigurationSync(MapBase.java:110) ~[vaadin-map-flow-23.2.0.beta4.jar:na]
	at com.vaadin.flow.component.map.MapBase.configurationPropertyChange(MapBase.java:135) ~[vaadin-map-flow-23.2.0.beta4.jar:na]
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343) ~[na:na]
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335) ~[na:na]
...
	at com.vaadin.flow.component.map.configuration.AbstractConfigurationObject.notifyChange(AbstractConfigurationObject.java:217) ~[vaadin-map-flow-23.2.0.beta4.jar:na]
...
	at com.vaadin.flow.component.map.configuration.AbstractConfigurationObject.notifyChange(AbstractConfigurationObject.java:207) ~[vaadin-map-flow-23.2.0.beta4.jar:na]
	at com.vaadin.flow.component.map.configuration.AbstractConfigurationObject.markAsDirty(AbstractConfigurationObject.java:135) ~[vaadin-map-flow-23.2.0.beta4.jar:na]
	at com.vaadin.flow.component.map.configuration.style.ImageStyle.setScale(ImageStyle.java:105) ~[vaadin-map-flow-23.2.0.beta4.jar:na]
	at com.vaadin.example.sightseeing.views.map.MapView.<init>(MapView.java:46) ~[classes/:na]
 ... 
	
	... 87 common frames omitted
```

### Expected outcome

No Exception is thrown

### Minimal reproducible example

```java
public class MapView extends VerticalLayout {

    private Map map = new Map();
    public MapView() {
        setSizeFull();

        View view = map.getView();
        Coordinate center = new Coordinate(22.3, 60.452);
        view.setCenter(center);
        view.setZoom(14);
        
        MarkerFeature.PIN_ICON.setScale(0.30f);

        MarkerFeature feat = new MarkerFeature(center, MarkerFeature.PIN_ICON);
        map.getFeatureLayer().addFeature(feat);
        addAndExpand(map);
    }

```

### Steps to reproduce

- curl -s -f 'https://start.vaadin.com/dl?&preset=latest-java&projectName=latest-java' -o latest-java.zip 
- unzip latest-java.zip 
- cd latest-java
- edit `src/main/java/com/vaadin/example/sightseeing/views/map/MapView.java` and reemplace `MapView` constructor with the code above
- mvn
- edit `src/main/java/com/vaadin/example/sightseeing/views/map/MapView.java` and add an empty line

After reloading you get the exception

### Environment

Vaadin version(s):  23.2

### Browsers

Issue is not browser related

**Comment by sissbruecker** [comment]
As discussed in Slack, this issue existed since the original implementation and is not a new issue / blocker for PiT.

Opened an issue for it: https://github.com/vaadin/flow-components/issues/3647
