### ISSUE TITLE
`AvatarI18n` and `AvatarGroupI18n` should use default messages for null values

### ISSUE THREAD

**Issue by Frettman** [vaadin/flow-components#3824]
### Description

The I18n objects of other components, like DatePicker, allow null values and just use their default messages in that case.

- `AvatarI18n` and `AvatarGroupI18n` both throw an exception when trying to set a null value (which is inconsistent with other I18n classes).
- `Avatar` does not default to its default value when assinging an `AvatarI18n` on which `AvatarI18n#setAnonymous` has never been called. It just displays `null` in its tooltip.
- `AvatarGroup` triggers the following (truncated) stacktrace when not all messages on its `AvatarGroupI18n` have been set.

```
java.lang.NullPointerException: null
	at elemental.json.impl.JsonUtil.quote(JsonUtil.java:208) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JsonUtil$StringifyJsonVisitor.visit(JsonUtil.java:96) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JreJsonString.traverse(JreJsonString.java:81) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:177) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:177) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:177) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:177) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:72) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:281) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:267) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:252) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at elemental.json.impl.JreJsonObject.toJson(JreJsonObject.java:163) ~[gwt-elemental-2.8.2.vaadin2.jar:2.8.2.vaadin2]
	at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:153) ~[flow-server-23.2.0.jar:23.2.0]
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:116) ~[flow-server-23.2.0.jar:23.2.0]
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-23.2.0.jar:23.2.0]
```

### Expected outcome

- For consistency's sake, `AvatarI18n` and `AvatarGroupI18n` should allow null values to be set.
- `Avatar` and `AvatarGroup` should fall back to their default texts when individual messages are not set.

### Minimal reproducible example

´´´java
// the tooltip will be null
Avatar avatar = new Avatar();
avatar.setI18n(new AvatarI18n());
´´´
´´´java
// will trigger the above stacktrace
AvatarGroup avatar = new AvatarGroup();
avatar.setI18n(new AvatarGroupI18n());
´´´

### Steps to reproduce

Add the snippets to a view.

### Environment

Vaadin version(s): 23.2.3 
OS: Windows 10

**Comment by web-padawan** [comment]
Fixed by adding support for partial `i18n` to web components and covered by https://github.com/vaadin/flow-components/pull/8583. Closing.
