### ISSUE TITLE
IllegalArgumentException when 

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow-components#3838]
### Description

When I call tabs.getSelectedTab() an exception is thrown.

12:05:37.012 [http-nio-8080-exec-4] ERROR com.foo.ErrorHandler - Uncaught exception or error 7fd80967-a067-4523-aa9a-8b7e6e45e068: java.lang.IllegalArgumentException: The 'index' argument should not be greater than or equals to the number of children components. It was: 0
	at com.vaadin.flow.component.HasOrderedComponents.lambda$getComponentAt$0(HasOrderedComponents.java:126)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at com.vaadin.flow.component.HasOrderedComponents.getComponentAt(HasOrderedComponents.java:126)
	at com.vaadin.flow.component.tabs.Tabs.getSelectedTab(Tabs.java:360)
	at com.foo.ui.view.performanceplanning.ActivityComp.getSelectedActivity(ActivityComp.java:358)

### Expected outcome

I guess I shouldn't even be able to mess up the state of the 'Tabs' object so that its complex invariant is broken.
Hence, let me expect that setSelectedIndex(int) at least checks for validity.

### Minimal reproducible example

```
package com.vaadin.qa.views.helloworld;


import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.tabs.Tabs;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.RouteAlias;


@PageTitle("Hello World")
@Route(value = "hello")
@RouteAlias(value = "")
public class HelloWorldView extends VerticalLayout {
    public HelloWorldView() {
        setSizeFull();

        Tabs tabs = new Tabs();
        tabs.setSelectedIndex(0);

        if (tabs.getSelectedTab() != null) {
            Notification.show("Good - where there is no tab, none can be selected.");
        }

    }

}

```

### Steps to reproduce

use above example

### Environment

Vaadin version(s): 23.2.2
OS: macOS latest

### Browsers

Issue is not browser related

**Comment by TatuLund** [comment]
I think this is a borderline case whether this is a bug or not.

The first point is `tabs.setSelectedIndex(0);` , which in this case is illegal operation as there is no children. Hence setting index 0 is not valid. This is not enforced as `Tabs `can be defined also in a template and injected using `@Id` , and then there is no children synced to server, although they exists. I.e. attempt of doing the parameter check here and throwing `IllegalArgumentException` earlier than later, would make `Tabs `unusable with templates.

Based on the above argument, the fact you are getting `IllegalArgumentException` is sort of correct.

There is however another kind of problem in the code of `getSelectedTab() `method. Analogous what I said above, the children does not exists server side, and  it does not work with templates by design. There should be possibly a note about this in JavaDoc. If this is accepted behavior, then it would be possible to improve the method by catching  `IllegalArgumentException` and throwing  `IllegalStateException` with more intuitive message like: "Can't get selected a Tab when there are none. Tab is either on template or setSelectedTab(int) is used with wrong parameter value."

**Comment by enver-haase** [comment]
As far as I can remember, Tabs is broken for templates entirely? Certainly, you cannot create a Tabs with a number of Tab in Vaadin Designer.

**Comment by enver-haase** [comment]
> Hence setting index 0 is not valid. This is not enforced as `Tabs `can be defined also in a template and injected using `@Id`

I don't see why `@Id` tabs need to setSelectedIndex( XXX ) for any empty tabs?!

**Comment by samie** [comment]
This code indeed looks like it should fail with a `IndexOutOfBoundsException`:
        Tabs tabs = new Tabs();
        tabs.setSelectedIndex(0);

But `getSelectedTab` could just return `null` for convenience instead of an exception.

**Comment by xdenser** [comment]
I also observe this error in logs but with
@ClientCallable
com.vaadin.flow.component.tabs.Tabs.updateSelectedTab(boolean) on stack trace
unfortunatelly i cannot reproduce the problem
users just click something in the APP and this error appears
there is no my code on stack trace so this looks like Vaadin bug

**Comment by web-padawan** [comment]
Duplicate of https://github.com/vaadin/flow-components/issues/5214 which has been fixed by https://github.com/vaadin/flow-components/pull/6543. Closing.
