### ISSUE TITLE
Investigate failing LitRenderer ITs

### ISSUE THREAD

**Issue by web-padawan** [vaadin/flow-components#4139]
### Description

The following ITs started to fail:

```
15:43:18     shouldRenderWithNoBoundValueProviders[ANY_Chrome_]
15:43:18       org.junit.ComparisonFailure: expected:<[]0> but was:<[Item: ]0>
15:43:18       org.junit.ComparisonFailure: expected:<[]0> but was:<[Item: ]0>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at com.vaadin.flow.data.renderer.tests.LitRendererIT.shouldRenderWithNoBoundValueProviders(LitRendererIT.java:48)
```

```
15:43:18     shouldRemoveTheRenderer[ANY_Chrome_]
15:43:18       org.junit.ComparisonFailure: expected:<[[object Object]]> but was:<[Item: 0]>
15:43:18       org.junit.ComparisonFailure: expected:<[[object Object]]> but was:<[Item: 0]>  at org.junit.Assert.assertEquals(Assert.java:117)  at org.junit.Assert.assertEquals(Assert.java:146)  at com.vaadin.flow.data.renderer.tests.LitRendererIT.shouldRemoveTheRenderer(LitRendererIT.java:55)
```

```
15:43:18     shouldSupportRendererInstanceSpecificProperties[ANY_Chrome_]
15:43:18       org.junit.ComparisonFailure: expected:<[Details: 0 (details)]> but was:<[]>
15:43:18       org.junit.ComparisonFailure: expected:<[Details: 0 (details)]> but was:<[]>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at com.vaadin.flow.data.renderer.tests.LitRendererIT.shouldSupportRendererInstanceSpecificProperties(LitRendererIT.java:119)
```

### Expected outcome

Tests should pass.

### Environment

Vaadin version(s): 24.0 (latest master)

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment]
Looks like the issue was caused by https://github.com/vaadin/flow-components/pull/4127not backported to 23.3 branch. Closing.
