### ISSUE TITLE
NullPointerException when instantiating Upload outside of current UI context

### ISSUE THREAD

**Issue by archiecobbs** [vaadin/flow-components#4204]
### Description

If executing with a current `VaadinSession` but not with a current `UI`, then instantiating an `Upload` object causes a `NullPointerException`.

My code simply looks like this:
```java
final Upload newUpload = new Upload();
```
This is the exception that is thrown:
```
java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.component.UI.getUIId()" because the return value of "com.vaadin.flow.component.UI.getCurrent()" is null
	at com.vaadin.flow.server.communication.StreamRequestHandler.generateURI(StreamRequestHandler.java:148)
	at com.vaadin.flow.server.StreamResourceRegistry.getURI(StreamResourceRegistry.java:144)
	at com.vaadin.flow.server.StreamResourceRegistry.getURI(StreamResourceRegistry.java:127)
	at com.vaadin.flow.server.StreamResourceRegistry.getTargetURI(StreamResourceRegistry.java:139)
	at com.vaadin.flow.internal.nodefeature.ElementAttributeMap.doSetResource(ElementAttributeMap.java:157)
	at com.vaadin.flow.internal.nodefeature.ElementAttributeMap.setResource(ElementAttributeMap.java:143)
	at com.vaadin.flow.dom.impl.BasicElementStateProvider.setAttribute(BasicElementStateProvider.java:332)
	at com.vaadin.flow.dom.Element.setAttribute(Element.java:341)
	at com.vaadin.flow.component.upload.Upload.<init>(Upload.java:90)
```

As far back as I can remember, it was always possible to create `Vaadin` UI widgets outside of the context of a current `UI`, and then attach them to a `UI` later. This behavior is violating that implicit behavior guarantee.

### Expected outcome

I expected no exception.

### Minimal reproducible example

```java
VaadinSession.getCurrent().access(Upload::new);
```

### Steps to reproduce

```java
VaadinSession.getCurrent().access(Upload::new);
```

### Environment

Vaadin version(s): 23.2.7
OS: MacOS

### Browsers

Issue is not browser related

**Comment by archiecobbs** [comment]
Thanks for the quick turnaround addressing this issue.
