### ISSUE TITLE
ComboBox Serialization issue in tomcat cluster

### ISSUE THREAD

**Issue by davidef** [vaadin/flow-components#4420]
### Description

Following the resolution of issue #3814 we updated our production environment to 23.2.11 but now we have a different issue that forced us to rollback again to 23.1.x.
The application is deployed to a docker ( image: tomcat:9-jdk17-temurin ) tomcat cluster with 3 active nodes.

```
java.lang.invoke.WrongMethodTypeException: expected (ComboBoxBase)Locale but found (ComboBoxBase)Locale
	at java.base/java.lang.invoke.Invokers.newWrongMethodTypeException(Invokers.java:523)
	at java.base/java.lang.invoke.Invokers.checkExactType(Invokers.java:532)
	at com.vaadin.flow.component.combobox.ComboBoxDataController.lambda$setDataProvider$9fbb9d72$1(ComboBoxDataController.java:457)
	at com.vaadin.flow.component.combobox.ComboBoxDataController.lambda$setDataProvider$13e91f97$1(ComboBoxDataController.java:484)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:258)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:709)
	at com.vaadin.flow.data.provider.ListDataProvider.size(ListDataProvider.java:87)
	at com.vaadin.flow.data.provider.DataCommunicator.getDataProviderSize(DataCommunicator.java:924)
	at com.vaadin.flow.data.provider.DataCommunicator.flush(DataCommunicator.java:1148)
	at com.vaadin.flow.data.provider.DataCommunicator.lambda$requestFlush$7258256f$1(DataCommunicator.java:1112)
	at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$2(StateTree.java:392)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.vaadin.flow.internal.StateTree.runExecutionsBeforeClientResponse(StateTree.java:389)
	at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:390)
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:174)
	at com.vaadin.flow.server.communication.UidlRequestHandler.createUidl(UidlRequestHandler.java:158)
	at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:146)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:116)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1564)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:369)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
```

### Expected outcome

No serialization issue

### Minimal reproducible example

The production code in not different from the one in  #3814 but we are unable to create a simple example causing the issue. In our test env (which is not clustered) where we do hot deploys it some time happen after few hot deploy of the app and undeploying and redeploying it fix the issue in the test env (without need to restart tomcat)

### Steps to reproduce

As in  #3814 it happen when clicking in a combobox to open the dropdown

### Environment

Vaadin version(s): 23.2.11
OS: docker tomcat:9-jdk17-temurin

**Comment by TatuLund** [comment]
My best guess is that the trouble maker is the function reference here. getLocale is inherited method, and some type erasure may happen, hence checkExactType throws.

https://github.com/vaadin/flow-components/blob/master/vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java#L151

**Comment by davidef** [comment]
@TatuLund We cherrypicked your patch (by overriding the ComboBoxBase class in our war over 23.2.11 release) in our test environment. So far we didn't manage to reproduce the issue on the test environment.
Due to holidays we are unable to give you more detailed feedback if it effectively fixed the issue because we can't deploy it on our production until the 9th of January where the issue was happening more frequently.

**Comment by davidef** [comment]
@TatuLund just a quick update we have been running in production with your patch since yesterday morning. At this time it seams that all is working as expected now.

**Comment by TatuLund** [comment]
@davidef Thanks for letting us know.
