### ISSUE TITLE
Notification TestBench Integration flaky

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow-components#4921]
### Description

Text of Notification isn't accessible by TestBench on first call.

### Expected outcome

Both tests are successful

### Minimal reproducible example

View Code: https://github.com/vaadin/web-components/issues/5665

Edit: it doesn't have to be within a dialog, a simple vertical layout is enough for the base of the button

Test based on: https://github.com/vaadin/testbench-demo

```java

public class SimpleIT extends AbstractIT {

    @Test
    public void testWithOneCall() {
        $(ButtonElement.class).first().click();

        Assertions.assertEquals("Show me for 10 Seconds",
          $(NotificationElement.class).waitForFirst(10).getText());
    }

    @Test
    public void testWithTwoCalls() {
        $(ButtonElement.class).first().click();

        $(NotificationElement.class).waitForFirst(2).getText(); // if I call it twice.. it works.. don't ask me why......

        Assertions.assertEquals("Show me for 10 Seconds",
          $(NotificationElement.class).waitForFirst(10).getText());
    }

}

```

```log

[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.971 s <<< FAILURE! - in com.vaadin.testbenchexample.SimpleIT
[ERROR] com.vaadin.testbenchexample.SimpleIT.testWithOneCall  Time elapsed: 6.068 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <Show me for 10 Seconds> but was: <>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1142)
	at com.vaadin.testbenchexample.SimpleIT.testWithOneCall(SimpleIT.java:21)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SimpleIT.testWithOneCall:21 expected: <Show me for 10 Seconds> but was: <>
[INFO] 
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0


```
Env: MacOS / Chrome 110-112

### Steps to reproduce

1. Create a view based of the web components example
2. Use the SimpleIT test provided here
3. Execute 

### Environment

Vaadin version(s):  24
OS: MacOS / Unix

### Browsers

Chrome

**Comment by knoobie** [comment]
@tomivirkki Could reproduce it, if you need the full diff based on testbench-demo, I can provide you that as well

**Comment by Artur-** [comment]
It is a timing issue caused by the notification element first being added to the DOM while empty and only rendered after a very short delay. TestBench finds the element and gets the text (empty at that point) before the content is rendered

**Comment by knoobie** [comment]
Thanks for confirming Artur!

**Comment by tomivirkki** [comment]
Did some more investigation on this. The text content is there but `WebElement.getText()` for some reason returns empty. If you use `((TestBenchElement) $(NotificationElement.class).first().getContext()).getProperty("textContent")` instead, it works just fine.

Weirdly, the issue doesn't manifest if you don't change the notification's position from the default (with `notification.setPosition(Position.BOTTOM_END);`)
