### ISSUE TITLE
Grid breaks with internal error (IllegalStateException) instead of IllegalArgumentException

### ISSUE THREAD

**Issue by edler-san** [vaadin/flow-components#5067]
### Description

I tried adding an extra header row for a single column. Neither does the API enforce nor does the documentation mentions any constraints here.

### Expected outcome

When joining a single column in a HeaderRow I expect either a single column header row or an exception telling me I need at least two cells to join; which, while it is coded (AbstractRow#L261), is not documented. Instead I get a stacktrace indicating some internal error.

### Minimal reproducible example

```java
        Grid<String> grid = new Grid<>(String.class, false);
        Grid.Column<String> lowerColumn = grid.addColumn(String::toLowerCase).setHeader("lower");
        Grid.Column<String> upperColumn = grid.addColumn(String::toUpperCase).setHeader("upper");

        HeaderRow headerRow = grid.prependHeaderRow();
        headerRow.join(lowerColumn).setText("Joint");
        add(grid);
```

### Steps to reproduce

Add the snippet and load the view.

You get a stacktrace like: 
```
There was an unexpected error (type=Internal Server Error, status=500).
java.lang.IllegalStateException: Can't move a node from one state tree to another. If this is intentional, first remove the node from its current state tree by calling removeFromTree
com.vaadin.flow.server.ServiceException: java.lang.IllegalStateException: Can't move a node from one state tree to another. If this is intentional, first remove the node from its current state tree by calling removeFromTree
	at com.vaadin.flow.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1629)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1592)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:252)
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:111)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:353)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:313)
	at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Can't move a node from one state tree to another. If this is intentional, first remove the node from its current state tree by calling removeFromTree
	at com.vaadin.flow.internal.StateNode.doSetTree(StateNode.java:731)
	at com.vaadin.flow.internal.StateNode.lambda$setTree$3(StateNode.java:372)
	at com.vaadin.flow.internal.StateNode.visitNodeTree(StateNode.java:680)
	at com.vaadin.flow.internal.StateNode.setTree(StateNode.java:372)
	at com.vaadin.flow.internal.StateNode.setParent(StateNode.java:272)
	at com.vaadin.flow.internal.nodefeature.NodeFeature.attachPotentialChild(NodeFeature.java:80)
	at com.vaadin.flow.internal.nodefeature.StateNodeNodeList.add(StateNodeNodeList.java:55)
	at com.vaadin.flow.internal.nodefeature.ElementChildrenList.add(ElementChildrenList.java:44)
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.insertChild(AbstractNodeStateProvider.java:104)
	at com.vaadin.flow.dom.Node.insertChild(Node.java:294)
	at com.vaadin.flow.dom.Node.appendChild(Node.java:141)
	at com.vaadin.flow.component.internal.UIInternals.showRouteTarget(UIInternals.java:744)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:259)
	at com.vaadin.flow.router.internal.ErrorStateRenderer.handle(ErrorStateRenderer.java:105)
	at com.vaadin.flow.router.Router.handleExceptionNavigation(Router.java:299)
	at com.vaadin.flow.router.Router.navigate(Router.java:234)
	at com.vaadin.flow.router.Router.navigate(Router.java:198)
	at com.vaadin.flow.router.Router.initializeUI(Router.java:95)
	at com.vaadin.flow.server.BootstrapHandler.initializeUIWithRouter(BootstrapHandler.java:1684)
	at com.vaadin.flow.server.BootstrapHandler.createAndInitUI(BootstrapHandler.java:1677)
	at com.vaadin.flow.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:511)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1580)
	... 52 more
```

### Environment

Vaadin version(s): 14.9.7
OS: Win 11, Edge 113.0.1774.42, Firefox 113.0.1

### Browsers

Issue is not browser related

**Comment by sissbruecker** [comment]
The JavaDoc could be improved to mention that joining requires at least two cells.

However I could not reproduce the exception from the provided example. From my testing the exception's stacktrace correctly contains the following root exception:
```
Caused by: java.lang.IllegalArgumentException: Cannot join less than 2 cells
        at com.vaadin.flow.component.grid.AbstractRow.join(AbstractRow.java:262)
        at com.vaadin.flow.component.grid.HeaderRow.join(HeaderRow.java:109)
        at com.vaadin.flow.component.grid.HeaderRow.join(HeaderRow.java:85)
        at com.vaadin.flow.component.grid.it.JoinPage.<init>(JoinPage.java:16)
        ... 62 more
```

**Comment by edler-san** [comment]
[illegalstate.zip](https://github.com/vaadin/flow-components/files/11552847/illegalstate.zip)
Start via `mvn spring-boot:run` and navigate to localhost:8080/foo

**Comment by sissbruecker** [comment]
I'm also getting `java.lang.IllegalArgumentException: Cannot join less than 2 cells` from the example project.
