### ISSUE TITLE
DataProvider types swapped at runtime (?)

### ISSUE THREAD

**Issue by FelixGaebler** [vaadin/flow-components#5400]
### Description of the bug

We have created a custom DataProvider to serve a ComboBox and a Crud at the same time. Unfortunately Vaadin seems to swap the types at runtime, which leads to the following error: 
```
java.lang.ClassCastException: class com.vaadin.flow.component.crud.CrudFilter cannot be cast to class java.lang.String (com.vaadin.flow.component.crud.CrudFilter is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
	at de.dataport.bugs.views.shared.AbstractRepositoryImpl.fetch(AbstractRepositoryImpl.java:35) ~[classes/:na]
	at de.dataport.bugs.views.shared.AbstractRepositoryImpl.count(AbstractRepositoryImpl.java:50) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:288) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:516) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:628) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:168) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:77) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-6.0.9.jar:6.0.9]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391) ~[spring-tx-6.0.9.jar:6.0.9]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.0.9.jar:6.0.9]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-6.0.9.jar:6.0.9]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:163) ~[spring-data-jpa-3.1.0.jar:3.1.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223) ~[spring-aop-6.0.9.jar:6.0.9]
	at jdk.proxy4/jdk.proxy4.$Proxy123.count(Unknown Source) ~[na:na]
	at de.dataport.bugs.views.report2.CustomDataProvider.sizeInBackEnd(CustomDataProvider.java:34) ~[classes/:na]
	at com.vaadin.flow.data.provider.AbstractBackEndDataProvider.size(AbstractBackEndDataProvider.java:66) ~[flow-data-24.1.6.jar:24.1.6]
	at com.vaadin.flow.data.provider.DataProviderWrapper.size(DataProviderWrapper.java:85) ~[flow-data-24.1.6.jar:24.1.6]
	at com.vaadin.flow.data.provider.DataCommunicator.getDataProviderSize(DataCommunicator.java:924) ~[flow-data-24.1.6.jar:24.1.6]
	at com.vaadin.flow.data.provider.DataCommunicator.flush(DataCommunicator.java:1159) ~[flow-data-24.1.6.jar:24.1.6]
	at com.vaadin.flow.data.provider.DataCommunicator.lambda$requestFlush$7258256f$1(DataCommunicator.java:1123) ~[flow-data-24.1.6.jar:24.1.6]
	at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$2(StateTree.java:392) ~[flow-server-24.1.6.jar:24.1.6]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at com.vaadin.flow.internal.StateTree.runExecutionsBeforeClientResponse(StateTree.java:389) ~[flow-server-24.1.6.jar:24.1.6]
	at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:394) ~[flow-server-24.1.6.jar:24.1.6]
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:170) ~[flow-server-24.1.6.jar:24.1.6]
	at com.vaadin.flow.server.communication.UidlRequestHandler.createUidl(UidlRequestHandler.java:155) ~[flow-server-24.1.6.jar:24.1.6]
	at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:145) ~[flow-server-24.1.6.jar:24.1.6]
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:115) ~[flow-server-24.1.6.jar:24.1.6]
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-24.1.6.jar:24.1.6]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1529) ~[flow-server-24.1.6.jar:24.1.6]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398) ~[flow-server-24.1.6.jar:24.1.6]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106) ~[vaadin-spring-24.1.6.jar:na]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.8.jar:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:642) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:408) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:313) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:277) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
	at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) ~[spring-webmvc-6.0.9.jar:6.0.9]
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:178) ~[spring-webmvc-6.0.9.jar:6.0.9]
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51) ~[spring-webmvc-6.0.9.jar:6.0.9]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.9.jar:6.0.9]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.9.jar:6.0.9]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.9.jar:6.0.9]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.0.9.jar:6.0.9]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[tomcat-embed-core-10.1.8.jar:6.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.9.jar:6.0.9]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.8.jar:6.0]
```

Here is the type-swap:
https://github.com/vaadin/flow/blob/main/flow-data/src/main/java/com/vaadin/flow/data/provider/DataProviderWrapper.java#L44

### Expected behavior

DataProvider should work. No exception should be thrown.

### Minimal reproducible example

https://github.com/FelixGaebler/vaadin-bugs/tree/master/src/main/java/de/dataport/bugs/views/report2

```java
public class CustomDataProvider<E extends AbstractEntity, R extends AbstractRepository<E>>
        extends AbstractBackEndDataProvider<E, String>
        implements ConfigurableFilterDataProvider<E, String, CrudFilter> {

    private final R repository;

    @Getter
    @Setter
    private CrudFilter filter;

    public CustomDataProvider(R repository) {
        this.repository = repository;
    }

    @Override
    protected Stream<E> fetchFromBackEnd(Query<E, String> query) {
        return this.repository.fetch(query, this.filter);
    }

    @Override
    protected int sizeInBackEnd(Query<E, String> query) {
        return this.repository.count(query, this.filter);
    }

}
```

### Versions

- Vaadin / Flow version: 24.1.5
- Java version: 17
- OS version: Ubuntu 22

**Comment by FelixGaebler** [comment]
The implementation of the `ConfigurableFilterDataProvider` leads one to believe that one can build a `DataProvider<T, Q>` with an additional filter `C`. [Vaadin Flow Repo](https://github.com/vaadin/flow/blob/main/flow-data/src/main/java/com/vaadin/flow/data/provider/ConfigurableFilterDataProvider.java)

Perhaps this is also a documentation issue for Vaadin's `DataProvider`s. The methods like `withConvertedFilter` are also only documented in the source code and the handling is unfortunately difficult or even impossible to understand.

There are two reasons why I tried to implement the DataProvider this way, maybe this can be solved differently:

1. I would like to have own filter criteria above the `Crud`, but not lose the functionality of the `Crud`. Unfortunately there is only one `setFilter` and no `getFilter` function in the `ConfigurableFilterDataProvider`, so you can't extend the filter but only replace it.
2. The filters are unfortunately only string values. Sometimes it is necessary to include more complex filters (e.g. lowerThan, like, ...) which in my eyes can currently only be implemented via dirty cocatenations (z.B. `"LOWER_33"`).

In the end, I end up overriding a `CrudFilter` and adding additional functionality.
```java
public class Filter extends CrudFilter {

    public enum Function {
        GREATER, GREATER_EQUALS, LOWER, LOWER_EQUALS, LIKE, EQUALS
    }

    private final Map<String, Function> functions = new LinkedHashMap<>();

}
```

It would be nicer if I actually had all the types (`T`, `Q`, `C`) and could work with them in the repository:
```java
public Stream<E> fetch(Query<E, String> query, CrudFilter filter) {
	CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();
	CriteriaQuery<E> criteriaQuery = builder.createQuery(this.entityClass);
	Root<E> root = criteriaQuery.from(this.entityClass);
	criteriaQuery.select(root);

	query.getFilter().ifPresent(queryFilter -> {
		//TODO apply query filter
	});

	Optional.ofNullable(filter).ifPresent(crudFilter -> {
		//TODO apply crud filter
	});

	return this.entityManager.createQuery(criteriaQuery)
			.setFirstResult(query.getOffset())
			.setMaxResults(query.getLimit())
			.getResultList().stream();
}
```
[My Code Example Repo](https://github.com/FelixGaebler/vaadin-bugs/blob/master/src/main/java/de/dataport/bugs/views/shared/AbstractRepositoryImpl.java#L29)

**Comment by Legioth** [comment]
The filter that the user applies in `Crud` is always in the form of a `CrudFilter` object that contains a map of String constraints based on what the user has entered into the filter component for that given grid column. Since `Crud` doesn't on its own support creating any other types of filter components, then the filter object it creates doesn't have to support anything beyond `Map<String, String>`.

What you might what to do is to make your `ComobBox` use a data provider that converts the filter provided by the user (i.e. a string typed into the field in the component) into a `CrudFilter` instance that your "generic" data provider implementation can use.

When you have a `DataProvider<Data, CrudFilter>` that for `Crud`, you can create a `DataProvider<Data, String>` for `ComboBox` like this:
```java
DataProvider<Data, String> comboBoxDataProvider = crudDataProvider.withConvertedFilter(String comobBoxFilterString -> {
  CrudFilter crudFilter = new CrudFilter();
  crudFilter.getConstraints().put("someProperty", comobBoxFilterString);
  return crudFilter;
});
```

If you want the combo box search to be based on a specific property in the data provider, then you can use that property name directly. If you want filtering to be based on multiple properties, then you can have the data provider implementation look for `someProperty` and use that to configure the query accordingly.

The purpose of `ConfigurableFilterDataProvider` is in the case when you get some filter input from the U component using the data provider (e.g. filter text typed into a combo box) and you also have an "external" filter (e.g. a standalone `TextField` that knows nothing about the data provider). `ConfigurableFilterDataProvider` gives a way of combining both filter inputs into a single value that the generic data provider can use to actually query the data. The fundamental idea is that a data provider always receives a single value as the filter. You can use the type system in Java to support different cases by introducing a DTO or by using polymorphism.

**Comment by FelixGaebler** [comment]
You could make use of this functionality by building your own filter object, which inherits from `CrudFilter` and writes a `Repository`/`DataProvider` for it. Given is a `DataProvider<Data, DataFilter>`. How do I now use `withConvertedFilter` to make a `DataProvider<Data, CrudFilter>` out of it?  The method seems to work somehow unintuitively the wrong way around.

It also seems to me like a `Crud` is generally incompatible with `ConfigurableFilterDataProvider`, right?

**Comment by Legioth** [comment]
> How do I now use `withConvertedFilter` to make a `DataProvider<Data, CrudFilter>` out of it? The method seems to work somehow unintuitively the wrong way around.

I can't address the intuitiveness without hearing how you expect it to behave.

The most essential part of the concept is that UI components that support filtering pass a filter definition as part of every data request that it sends to the data provider. The way `withConvertedFilter` works is that the converter receives a filter value provided by the UI component that uses the data provider and converts it to a filter value expected by the data provider.

`ConfigurableFilterDataProvider` can work with `Crud` if it's used in a certain way. The core concept here is that filter values for a data request can by default only come from the UI component that requests the data. A "configurable" provider does additionally allow application logic to directly "configure" the data provider to use some other filter in the requests passed to the the underlying data provider when the UI component requests data (by running `setFilter`).

There are two overloads of `withConfigurableFilter`. The zero-argument variant creates a data provider that ignores filters from the UI component and only uses the filter passed to `setFilter`. The other variant takes a callback for combining the component filter (if any) with the application filter (if any) into a single filter for the underlying data provider. If you want filters from `Crud` to be taken into account with a `ConfigurableFilterDataProvider`, then you need to create it using the overload that combines filters from both sources rather than ignoring the filter value from the UI component.

**Comment by yuriy-fix** [comment]
Closing the issue as stale. Feel free to reopen if still valid.
