### ISSUE TITLE
TreeGrid: Children are lost when drag & drop a node (not a leaf)

### ISSUE THREAD

**Issue by leewatt** [vaadin/flow-components#5530]
### Description
Modify sample code _GridDragDropFilters.java_ @ https://vaadin.com/docs/latest/components/grid#drag-drop

1. Set drag filter off
```
        grid.setRowsDraggable(true);
        grid.setDropMode(GridDropMode.ON_TOP_OR_BETWEEN);

//// Only allow dragging staff
//        grid.setDragFilter(person -> !person.isManager());
//// Only allow dropping on managers
//        grid.setDropFilter(person -> person.isManager());
```

2. Drag and drop a root node into another, the children of the node are lost.
3. This issue also exists when the node is a child. 

### Expected outcome

The node and its children should be dropped together.  

### Minimal reproducible example

See Part1.

### Steps to reproduce

See Part1.

### Environment

Vaadin version(s): 24.1.8
OS: Windows 10， x64

### Browsers

Firefox, Edge

**Comment by ugur-vaadin** [comment]
This is not actually a bug, but an issue with the example in the documentation. When `TreeData.remove` is called, it is expected that the item loses its children in the tree. To update the parent, `TreeData.setParent` should be used instead. I submitted a [PR](https://github.com/vaadin/docs/pull/2868) to update the example to in order to avoid future misunderstandings.

**Comment by leewatt** [comment]
Follow your instruction and find it doesn't work when the node is collapsed.
1. Drag a node with child/children collapsed.
2. Drop it on top of another node or drop it below/above another node in another branch.
3. The node seems to be moved correctly.
4. Expand the node, no child/children is/are attached, and following exception is reported:
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:208) ~[na:na]
	at java.base/java.util.ImmutableCollections$List12.<init>(ImmutableCollections.java:556) ~[na:na]
	at java.base/java.util.List.of(List.java:812) ~[na:na]
	at com.vaadin.flow.component.treegrid.TreeGrid.lambda$addHierarchyColumn$63241ece$1(TreeGrid.java:583) ~[vaadin-grid-flow-24.1.8.jar:na]
	at com.vaadin.flow.data.renderer.LitRenderer.lambda$withFunction$71d1d723$1(LitRenderer.java:330) ~[vaadin-renderer-flow-24.1.8.jar:na]
	at com.vaadin.flow.data.renderer.LitRenderer.lambda$createJsRendererFunction$f31f4741$1(LitRenderer.java:205) ~[vaadin-renderer-flow-24.1.8.jar:na]
	at com.vaadin.flow.internal.nodefeature.ReturnChannelMap.lambda$registerChannel$2a20409b$1(ReturnChannelMap.java:124) ~[flow-server-24.1.10.jar:24.1.10]
	at com.vaadin.flow.internal.nodefeature.ReturnChannelMap$ChannelImpl.invoke(ReturnChannelMap.java:74) ~[flow-server-24.1.10.jar:24.1.10]
	at com.vaadin.flow.server.communication.ReturnChannelHandler.handleNode(ReturnChannelHandler.java:78) ~[flow-server-24.1.10.jar:24.1.10]
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:74) ~[flow-server-24.1.10.jar:24.1.10]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:459) ~[flow-server-24.1.10.jar:24.1.10]
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$2(ServerRpcHandler.java:440) ~[flow-server-24.1.10.jar:24.1.10]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
...

**Comment by ugur-vaadin** [comment]
That is a separate issue and was [fixed](https://github.com/vaadin/flow/pull/17774) recently. It was also back-ported to v24.1, therefore should be available with the next patch release.
