### ISSUE TITLE
Dialog and Notification cannot be used with Session Replication

### ISSUE THREAD

**Issue by MichaelPluessErni** [vaadin/flow-components#5597]
When trying to use Session Replication with Vaadin, the Deserialization fails when a Notification or a nested Dialog is present on the webpage. The error is the exact situation described here:
https://vaadin.com/docs/latest/tools/kubernetes/session-replication#serializedlambda-classcastexception

This is a problem as these components are attached to the view and thus the VaadinSession and thus cannot be excluded from serialization.

Example 1: Inside a Dialog, a button is clicked that opens a ConfirmDialog, without closing the Dialog
Output from Kubernetes Kit - Session Replication Debug Tool:
```
ERRORS DURING SERIALIZATION/DESERIALIZATION PROCESS:
====================================================
DESERIALIZATION_FAILED: cannot assign instance of java.lang.invoke.SerializedLambda to field com.vaadin.flow.component.dialog.Dialog.childDetachListener of type com.vaadin.flow.dom.ElementDetachListener in instance of com.vaadin.flow.component.dialog.Dialog

SERIALIZED LAMBDA CLASS CAST EXCEPTION BEST CANDIDATES:
=======================================================
	SerializedLambda[capturingClass=class com.vaadin.flow.component.dialog.Dialog, functionalInterfaceMethod=com/vaadin/flow/dom/ElementDetachListener.onDetach:(Lcom/vaadin/flow/dom/ElementDetachEvent;)V, implementation=invokeVirtual com/vaadin/flow/component/dialog/Dialog.lambda$new$76f1ff5c$1:(Lcom/vaadin/flow/dom/ElementDetachEvent;)V, instantiatedMethodType=(Lcom/vaadin/flow/dom/ElementDetachEvent;)V, numCaptured=1]
	- field (class "com.vaadin.flow.dom.Element$2", name: "val$detachListener", type: "interface com.vaadin.flow.dom.ElementDetachListener")
[...]
```

End of associated StackTrace:
```
java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field com.vaadin.flow.component.dialog.Dialog.childDetachListener of type com.vaadin.flow.dom.ElementDetachListener in instance of com.vaadin.flow.component.dialog.Dialog
	at java.base/java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2227)
	at java.base/java.io.ObjectStreamClass$FieldReflector.checkObjectFieldValueTypes(ObjectStreamClass.java:2191)
	at java.base/java.io.ObjectStreamClass.checkObjFieldValueTypes(ObjectStreamClass.java:1478)
	at java.base/java.io.ObjectInputStream$FieldValues.defaultCheckFieldValues(ObjectInputStream.java:2657)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2471)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)
	at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1730)
	at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2584)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2442)
[...]
```

Example 2: Using a `Notification` inside a component:
```
class Example extends Div {
    Example() {
        render();
    }

    void render() {
        Notification notification = new Notification();
	notification.add(new Text("Test"));
	notification.open();
    }
}
```

Output from Kubernetes Kit - Session Replication Debug Tool:
```
ERRORS DURING SERIALIZATION/DESERIALIZATION PROCESS:
====================================================
DESERIALIZATION_FAILED: cannot assign instance of java.lang.invoke.SerializedLambda to field com.vaadin.flow.component.notification.Notification.childDetachListener of type com.vaadin.flow.dom.ElementDetachListener in instance of com.vaadin.flow.component.notification.Notification

SERIALIZED LAMBDA CLASS CAST EXCEPTION BEST CANDIDATES:
=======================================================
	SerializedLambda[capturingClass=class com.vaadin.flow.component.notification.Notification, functionalInterfaceMethod=com/vaadin/flow/dom/ElementDetachListener.onDetach:(Lcom/vaadin/flow/dom/ElementDetachEvent;)V, implementation=invokeVirtual com/vaadin/flow/component/notification/Notification.lambda$new$97ff97a6$1:(Lcom/vaadin/flow/dom/ElementDetachEvent;)V, instantiatedMethodType=(Lcom/vaadin/flow/dom/ElementDetachEvent;)V, numCaptured=1]
	- field (class "com.vaadin.flow.dom.Element$2", name: "val$detachListener", type: "interface com.vaadin.flow.dom.ElementDetachListener")
[...]
```

Same StackTrace as in first example.

Interestingly, the error does not occur when `Notification.show(...)` is used.

As far as I was able to track it down, those errors relate to the detach listeners that are set on the child elements in the respective `updateVirtualChildNodeIds()` of Dialog and Notification.
There seems to exist a reference loop: Notification -> Child Element -> Detach Listener -> Notification

This leads to the error during deserialization where Java tries to set a `SerializedLambda` on a `ElementDetachListener` field.

Used Vaadin Version: 24.2.0
Web container: Spring Boot 3.1.4
Expected: UI can be serialized and deserialized
Actual: Notification and certain Dialog constellations cannot be deserialized

**Comment by tomivirkki** [comment]
Hi @MichaelPluessErni 

I tried to reproduce the serialization error with no success. Maybe I'm lacking something from how the components are set up. Here's the test case that I used but it passes fine:

```java
package com.example;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;

import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.confirmdialog.ConfirmDialog;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.server.VaadinSession;
import com.vaadin.flow.server.WrappedSession;

public class SerializationTest {
    
    private UI ui;

    @Before
    public void setup() {
        ui = new UI();
        UI.setCurrent(ui);

        var session = Mockito.mock(VaadinSession.class);
        Mockito.when(session.hasLock()).thenReturn(true);
        var wrappedSession = Mockito.mock(WrappedSession.class);
        Mockito.when(session.getSession()).thenReturn(wrappedSession);

        ui.getInternals().setSession(session);
    }

    @Test
    public void DialogConfirmDialog() throws Throwable {
        // Example 1: Inside a Dialog, a button is clicked that opens a ConfirmDialog, without closing the Dialog
        var dialog = new Dialog();
        ui.add(dialog);
        var confirmDialog = new ConfirmDialog();
        var button = new Button("Open confirm dialog", event -> {
            confirmDialog.open();            
        });

        // Open the dialog
        dialog.open();
        flushBeforeClientResponse();

        // Click the button
        button.click();
        flushBeforeClientResponse();

        // Assert state

        // Dialog is a child of the ui
        Assert.assertEquals(ui, dialog.getParent().get());
        // Dialog is open
        Assert.assertTrue(dialog.isOpened());
        // ConfirmDialog is a child of the dialog
        Assert.assertEquals(dialog, confirmDialog.getParent().get());
        // ConfirmDialog is open
        Assert.assertTrue(confirmDialog.isOpened());

        // Serialize and deserialize
        var deserializedUI = (UI) serializeAndDeserialize(ui);
        var deserializedDialog = (Dialog) deserializedUI.getChildren().findFirst().get();
        var deserializedConfirmDialog = (ConfirmDialog) deserializedDialog.getChildren().findFirst().get();

        // Assert state after deserialization

        // Dialog is open
        Assert.assertTrue(deserializedDialog.isOpened());

        // ConfirmDialog is open
        Assert.assertTrue(deserializedConfirmDialog.isOpened());
    }

    private void flushBeforeClientResponse() {
        ui.getInternals().getStateTree().runExecutionsBeforeClientResponse();
        ui.getInternals().dumpPendingJavaScriptInvocations();
    }

    private Object serializeAndDeserialize(Object object) throws Throwable {
        var out = new ByteArrayOutputStream();
        var objectOutputStream = new ObjectOutputStream(out);

        objectOutputStream.writeObject(object);

        var inputStream = new ByteArrayInputStream(out.toByteArray());
        var objectInputStream = new ObjectInputStream(inputStream);

        var deserializedObject = objectInputStream.readObject();
        return deserializedObject;
    }    
}

```
Tried with Vaadin versions 24.3-SNAPSHOT, 24.2. Java versions 17 and 21.

**Comment by tomivirkki** [comment]
Was able to reproduce the issue in a local Kubernetes cluster. Fixing now.
