### ISSUE TITLE
NPE in TreeGrid (race condition) while refreshing and clicking hierachical column

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow-components#5778]
### Description

While refreshing the Grid and simultaneous clicking rapidly the hierachical column it's possible that the application throws an unexpected error: 

```java
2023-11-27T11:06:22.916+01:00 ERROR 979 --- [nio-7009-exec-3] c.v.flow.server.DefaultErrorHandler      :
java.lang.NullPointerException: null
  at java.base/java.util.Objects.requireNonNull(Unknown Source)
  at java.base/java.util.ImmutableCollections$List12.<init>(Unknown Source)
  at java.base/java.util.List.of(Unknown Source)
  at com.vaadin.flow.component.treegrid.TreeGrid.lambda$addHierarchyColumn$63241ece$1(TreeGrid.java:583)
  at com.vaadin.flow.data.renderer.LitRenderer.lambda$withFunction$71d1d723$1(LitRenderer.java:330)
  at com.vaadin.flow.data.renderer.LitRenderer.lambda$createJsRendererFunction$f31f4741$1(LitRenderer.java:205)
  at com.vaadin.flow.internal.nodefeature.ReturnChannelMap.lambda$registerChannel$2a20409b$1(ReturnChannelMap.java:124)
  at com.vaadin.flow.internal.nodefeature.ReturnChannelMap$ChannelImpl.invoke(ReturnChannelMap.java:74)
  at com.vaadin.flow.server.communication.ReturnChannelHandler.handleNode(ReturnChannelHandler.java:78)
  at  com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:74)
  at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:459)
  at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$2(ServerRpcHandler.java:440)
  at java.base/java.util.ArrayList.forEach(Unknown Source)
  at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:440)
  at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:323)
  at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:114)
  at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
  at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1529)
  at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398)
  at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106)
  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)


```

Solution: add a nullcheck before passing the value from the client to the data communicator 

https://github.com/vaadin/flow-components/blob/e39becb6cc49a96297a9e2a4a5aa039a68754992/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java#L580-L588

```java

if(null == item) {
  return;
}

```

### Expected outcome

No Error

### Minimal reproducible example

See comments below

### Environment

Vaadin version(s): 24.2.4

**Comment by knoobie** [comment]
- 24.2.4 
- In Memory 
- "Slow" Running operation that reloads all data (takes 3-4 seconds) (Complex Data Structure / A lot of Data) 
- The hierachical column can be clicked to open/close the entry -> doing this while the refresh is still in progress -> can throw this error, especially if the result set does not contain the old entry (hashCode) again

**Comment by knoobie** [comment]
Here is a MRE:

```java




    var treeGrid = new TreeGrid<MyObject>();
    treeGrid.addHierarchyColumn(MyObject::getName);
    treeGrid.setItems(List.of(new MyObject("name-1",
      List.of(new MyObject("name-2", Collections.emptyList())))
    ), MyObject::getChildren);

    add(treeGrid);
    add(new Button("Click me", e -> { // once this is clicked -> click open/close of the entry
      try {
        Thread.sleep(5000);
      } catch (InterruptedException ex) {
        throw new RuntimeException(ex);
      }
      treeGrid.setItems(List.of(new MyObject("name-1",
        List.of(new MyObject("name-2", Collections.emptyList())))
      ), MyObject::getChildren);
    }));

  

  @Data
  @AllArgsConstructor
  @EqualsAndHashCode(of = "id")
  static class MyObject {
    private final String id = UUID.randomUUID().toString();
    private String name;

    private List<MyObject> children;
  }

```

**Comment by bwajtr** [comment]
Thanks a lot @knoobie, with your example I'm able to reproduce the NPE every time I repeat the following steps:
1. Reload page
2. Click on "Click me" button
3. Wait for the loading indicator to appear
4. When it appears immediately click once to expand the tree item
5. When the loading finishes 
  -> The NPE appears in the log
  -> The tree node is in an expanded state, however, the grid does not show the child items
