### ISSUE TITLE
[Grid] scrollToEnd is always executed after scrollToStart regardless of their call order

### ISSUE THREAD

**Issue by vursen** [vaadin/flow-components#5880]
### Description

`scrollToEnd` gets always executed after `scrollToStart` regardless of their call order in the code.

### Expected outcome

When `scrollToStart` comes after `scrollToEnd`, I'd expect the grid to scroll to the end and then to the start.

### Minimal reproducible example

```java
@Route("grid")
public class GridView extends Div {
    public GridView() {
        Grid<String> grid = new Grid<>();
        grid.addColumn(item -> item);
        grid.setItems(IntStream.range(0, 1000).mapToObj(i -> "Item " + i).collect(Collectors.toList()));

        Button scrollToEndAndStart = new Button("scroll to end and start", event -> {
            grid.scrollToEnd();
            grid.scrollToStart();
        });

        add(grid, scrollToEndAndStart);
    }
}
```

### Steps to reproduce

1. Click "scroll to end and start"
2. See that the grid's scroll position is at the end while I'd expect it at the start

### Environment

Vaadin version(s): 24.4 and earlier
OS: Mac OS

**Comment by vursen** [comment]
With TreeGrid, it doesn't seem to work at all:

```java
Caused by: java.lang.IllegalArgumentException: start must not be greater than end
	at com.vaadin.flow.internal.Range.<init>(Range.java:151) ~[flow-server-24.4-SNAPSHOT.jar:24.4-SNAPSHOT]
	at com.vaadin.flow.internal.Range.withLength(Range.java:135) ~[flow-server-24.4-SNAPSHOT.jar:24.4-SNAPSHOT]
	at com.vaadin.flow.data.provider.DataCommunicator.setRequestedRange(DataCommunicator.java:343) ~[flow-data-24.4-SNAPSHOT.jar:24.4-SNAPSHOT]
```
