### ISSUE TITLE
NumberField: setValue fails at certain circumstances

### ISSUE THREAD

**Issue by JoMWal** [vaadin/flow-components#6229]
### Description

Vaadin 24.3.7 (vaadin.text-field-flow 24.3.7)

NumberField: setValue fails when 
- "step" value is set 
- "min" value is set to Double.NEGATIVE_INFINITY

### Expected outcome

Works also with Double.NEGATIVE_INFINITY

### Minimal reproducible example

```
public static void main(final String[] args)
{
    final NumberField numberField = new NumberField();
    numberField.setStep(1.0);
    numberField.setMin(Double.NEGATIVE_INFINITY);
    numberField.setValue(6.0);
}
```

### Steps to reproduce

Run "Minimal reproducible example".

### Environment

Vaadin version(s):  24.3.7
OS: Win64

**Comment by web-padawan** [comment]
The error is thrown at this code where `BigDecimal.valueOf(stepBasis)` is called. 

```
Caused by: java.lang.NumberFormatException: Character I is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:582)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:467)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:896)
	at java.base/java.math.BigDecimal.valueOf(BigDecimal.java:1354)
	at com.vaadin.flow.component.textfield.AbstractNumberField.isValidByStep(AbstractNumberField.java:391)
	at com.vaadin.flow.component.textfield.AbstractNumberField.checkValidity(AbstractNumberField.java:347)
	at com.vaadin.flow.component.textfield.AbstractNumberField.validate(AbstractNumberField.java:372)
```

https://github.com/vaadin/flow-components/blob/3eed25e052d2db98fbc93cea0c791cb5aa53aeeb/vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java#L387-L392

In this particular case, `Double.NEGATIVE_INFINITY` is the same as `absoluteMin` used by default. So you shouldn't really need to set it manually. However, we need to handle this case and prevent the error from being thrown.
